### ISSUE TITLE
Developer ID signature is missing in installer package

### ISSUE THREAD

**Issue by bitmanic** [apparition47/MailTrackerBlocker#1]
When I try to install this package, I get the following alert: 

> "MailTrackerBlocker.pkg" can't be opened because Apple cannot check it for malicious software.
> _This softare needs to be updated. Contact the developer for more information._

Apple doesn't recognize the software as having been produced by a verified developer. I know that I can open system preferences and overrule this security setting, but it's not a great user experience. How hard would it be to add a verified developer ID signature to these packages?

**Comment by apparition47** [comment]
Thanks for reporting. Looking into it. Thought I signed it correctly.

**Comment by apparition47** [comment]
[Release 0.3.0](https://github.com/apparition47/MailTrackerBlocker/releases/tag/0.3.0) is signed and notarized!

**Comment by bitmanic** [comment]
Thanks for your work on this, @apparition47!
