### ISSUE TITLE
Incompatible Plug-ins Disabled

### ISSUE THREAD

**Issue by CaptainCustard** [apparition47/MailTrackerBlocker#10]
After updating my Mail app, this is what I get every time I enable the plugin. Any workaround or solution?

> Mail has disabled the following plug-ins:
> 
> MailTrackerBlocker.mailbundle
> 
> Contact the makers of these plug-ins for versions that are compatible with Mail 14.0.

**Comment by apparition47** [comment]
What version of MailTrackerBlocker are you on? macOS version? Apple silicon or intel mac?

**Comment by CaptainCustard** [comment]
Thank you for the followup. I actually decided to uninstall and reinstall and it started working again. May I ask if the plugin update itself automatically or not? If not, is there away to enable that?

**Comment by apparition47** [comment]
No internal update mechanism now but you can use brew to keep it updated.
