### ISSUE TITLE
Don't Block Redirection Link or Only Block Spy Pixel (Dropbox invitation link broken)

### ISSUE THREAD

**Issue by ybbond** [apparition47/MailTrackerBlocker#102]
## Summary
Dropbox domain is included in the "bad domain list" here:
https://github.com/apparition47/MailTrackerBlocker/blob/175ad0d7cce52204c1c98611b9fcdbfe8a7f7989/Source/MTBBlockedMessage.m#L191
This breaks Dropbox invitation links.

## Expected behavior
- The "bad domain list" only blocks/prevent link that call image, tracking pixel, or prefetch data.
- If image source is from the "bad domain list", detect whether the image is small enough to be a tracking pixel
    - my logic is, even though large image can still track you, but chance is the email reader wants to see that.

## Image for details
<img width="334" alt="dropbox domain omitted" src="https://user-images.githubusercontent.com/25895873/113639901-69dfa700-96a4-11eb-8f28-4cede1fda8e1.png" style="outline:1px solid black;">

<img width="406" alt="blocked notif" src="https://user-images.githubusercontent.com/25895873/113639907-6c420100-96a4-11eb-802f-1fa1e4e60b4b.png" style="outline:1px solid black;">

**Comment by apparition47** [comment]
Thanks for the detailed report.

I'm going to limit the block list to `img` tags only since that appears to be the majority of trackers that I've come across so far. This change will be in 0.3.29 and will fix this issue

**Comment by ybbond** [comment]
can confirm this works! thank you very much 🎉

![Proof yeay](https://user-images.githubusercontent.com/25895873/113685439-7558bf80-96f0-11eb-83f0-09a8c180d651.png)
