### ISSUE TITLE
Big Sur, Mail 14.0: incompatible plug-ins disabled

### ISSUE THREAD

**Issue by jasonhan-vassar** [apparition47/MailTrackerBlocker#103]
Hi, so I've been using MailTrackerBlocker just fine until one day (not sure when exactly) it started giving me the error below:

<img width="260" alt="Screen Shot 2021-04-06 at 2 18 42 AM" src="https://user-images.githubusercontent.com/34594853/113667188-69ccb080-967e-11eb-9630-6a5ab3d35bd6.png">

After updating MTB to 0.3.29, I still get this error. I've tried uninstalling (deleting plug-in from Finder and installing) and even 0.3.28, both of which give me this error. Can anyone else reproduce this? Thanks for reading.

### System info
macOS: 11.1
Apple Mail: 14.0
MailTrackerBlocker: 0.3.29

**Comment by apparition47** [comment]
Not able to reproduce this issue myself.

Could you delete the `~/Library/Application\ Support/Mail/Plug-ins/Bundles/` dir (see [SpamSieve's guide](https://c-command.com/spamsieve/help/resetting-mail-s-privat)) then try reinstalling?

**Comment by jasonhan-vassar** [comment]
Thanks so much, it's working now! For anyone else with this issue, I quit Mail, deleted the folder, ran the installer, and reopened Mail. It was already enabled at launch.

**Comment by apparition47** [comment]
Awesome! Thanks for reporting back
