### ISSUE TITLE
Mailgun tracker not recognized

### ISSUE THREAD

**Issue by mogita** [apparition47/MailTrackerBlocker#108]
Hi @apparition47, A copy of the `eml` was sent to you.

### Environment

MailTrackerBlocker  v0.3.29
macOS v11.2.3
Apple Mail v14.0 (3654.60.0.2.21)

### Description

The tracking pixel's hostname resolved to an IP of AWS, accessing the IP in my browser triggered a download, and opening the downloaded file it showed some text reading "Mailgun Magnificent API". However the "X" icon didn't mark it as a known tracker.

**Comment by apparition47** [comment]
Thanks again for the contribution 🙇‍♂️

Had an initial look at the email; glad it was at least blocked. Will add this one to the list.

**Comment by apparition47** [comment]
Fixed in 0.4.1
