### ISSUE TITLE
mailtrackerblocker is not compatible with mail app 14.0 Big Sur

### ISSUE THREAD

**Issue by frederictison** [apparition47/MailTrackerBlocker#110]
Hello,
Since a while, I have this message when I launch mail app from my imac.
I tried first tu uninstall with bash because it was installed from *.pkg but the message remains. I tried then to install from brew but same issue !
Any clue ?
Regards
FT
<img width="301" alt="Capture d’écran 2021-04-26 à 07 14 56" src="https://user-images.githubusercontent.com/26030314/116032215-8c3f6180-a65f-11eb-9b8e-7cecc8ced439.png">

**Comment by apparition47** [comment]
Could I ask you to please try the [steps here for clearing the user plug-ins dir: `~/Library/Application Support/Mail/Plug-ins/Bundles/`](https://c-command.com/spamsieve/help/resetting-mail-s-privat)?

**Comment by apparition47** [comment]
Closing. Feel free to reopen if you have issues after clearing the plugins dir
