### ISSUE TITLE
Seems stuck downloading update, even though there is no update to download.

### ISSUE THREAD

**Issue by space-chicken** [apparition47/MailTrackerBlocker#115]
Even though there is no update available, the progress bar starts, and is stuck. 

<img width="522" alt="image" src="https://user-images.githubusercontent.com/74451130/120925056-54164e80-c6f4-11eb-94f5-b3b190a44ed2.png">

**Comment by apparition47** [comment]
Wow you jumped on 0.4.1 quite fast.

Did this window come up automatically or did you manually click on `ⓧ` > `...` > "check for updates"?

Looks like a UI issue with the progress bar. I'll fix this, thanks!

**Comment by space-chicken** [comment]
I checked it manually :)

**Comment by apparition47** [comment]
Fixed in 0.4.2, thanks!
