### ISSUE TITLE
Very minor "issue": Tracker report window does not look like how it's shown in the Releases page.

### ISSUE THREAD

**Issue by space-chicken** [apparition47/MailTrackerBlocker#116]
Expectation:
<img width="656" alt="118488797-122e6400-b757-11eb-9a68-b0e9c482fff8" src="https://user-images.githubusercontent.com/74451130/120925255-6644bc80-c6f5-11eb-8472-87943f20b776.png">

Reality:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/74451130/120925264-6f358e00-c6f5-11eb-84fa-ad37ba701674.png">

**Comment by apparition47** [comment]
Thanks for reporting again. Will fix the font issue.

The shield icon though is from Apple. I swapped it out just before release; that one I can't use.

**Comment by space-chicken** [comment]
Oh, it's alright, the shield looks good.

**Comment by apparition47** [comment]
Fixed in 0.4.2, thanks!
