### ISSUE TITLE
Tracker Report page: UI elements wrong colour while switching light/dark mode

### ISSUE THREAD

**Issue by space-chicken** [apparition47/MailTrackerBlocker#117]
<img width="768" alt="Screenshot 2021-06-06 at 6 48 01 PM" src="https://user-images.githubusercontent.com/74451130/120926401-511e5c80-c6fa-11eb-9f6e-efb609a07361.png">

<img width="768" alt="Screenshot 2021-06-06 at 6 47 13 PM" src="https://user-images.githubusercontent.com/74451130/120926414-5c718800-c6fa-11eb-9a26-2b6186a749f0.png">

**Comment by apparition47** [comment]
Fixed in 0.4.2, thanks!
