### ISSUE TITLE
update not appearing in Brew

### ISSUE THREAD

**Issue by glgray** [apparition47/MailTrackerBlocker#118]
I am trying to update to the latest and greatest version using Brew and it has not appeared. Do I simply need to be more patient or is there some other issue?

**Comment by apparition47** [comment]
The Homebrew team has to manually approve this update before it shows up on
the official list of casks. Sorry!

On the bright side, shouldn’t be an issue in the future as there’s a built
in update mechanism now.

**Comment by apparition47** [comment]
Merged 🚀

**Comment by dotsam** [comment]
Just as a heads up, it looks like since the formula is now flagged as `auto_update` that Homebrew won't install the latest version. I had to manually run
```
brew upgrade mailtrackerblocker
```
to get from 0.3.29 to 0.4.1, a `brew upgrade` alone didn't do it.
