### ISSUE TITLE
Tracker report page is too tall

### ISSUE THREAD

**Issue by phiw13** [apparition47/MailTrackerBlocker#119]
On a MacBookAir 2018 (screen: 2560 × 1600  Retina) the Tracker window is full height of the screen and slides under the Dock.

It is fine on my iMac (about 80% of screen height, eyeballing).

Nice update otherwise.

<img width="652" alt="Screen Shot 2021-06-07 at 11 59 01" src="https://user-images.githubusercontent.com/8944809/120953447-ef0c3880-c787-11eb-8941-ca32dfc398d3.png">

**Comment by apparition47** [comment]
Thanks for opening an issue! Will fix soon

**Comment by apparition47** [comment]
Fixed in 0.4.2

**Comment by phiw13** [comment]
Thank you, much better now.
