### ISSUE TITLE
No "Manage Plug-ins" option - Mail Version 11.5 (3445.9.7)

### ISSUE THREAD

**Issue by keithgould** [apparition47/MailTrackerBlocker#12]
The Mail Preferences - General tab does not offer a "Manage Plugins" option.
Running under 10.13.6 (17G14042)

**Comment by apparition47** [comment]
That's odd. 

How did you install this plugin? Was Mail properly closed and re-launched during install? I have an installer script that's supposed to quit Mail then run `sudo defaults write "/Library/Preferences/com.apple.mail" EnableBundles -bool YES` to enable the "Manage Plug-ins" option.

Could you try quitting Mail then trying that command again? [See this article for reference](https://help.mailbutler.io/help/manage-plug-ins-button-is-gone-from-apple-mail).

**Comment by keithgould** [comment]
Hi Aaron,

Many thanks for getting back to me.
I confess - the Apple Mail app was running when I did the instal; I didn’t quit it myself. I found, post install, that it was not running and re-launched it. It was after this that I noted the lack of enable option in the General Tab for mail prefs

Ran the command from Term - no errors but here’s what I see when I re-launch mail and open the general prefs

**Comment by apparition47** [comment]
Did you mean to attach a photo? I don't see it. I assume the command didn't work? 

Could you try other commands in the [article above](https://help.mailbutler.io/help/manage-plug-ins-button-is-gone-from-apple-mail)?

**Comment by keithgould** [comment]
HI

Yes I attached a snapshot of the Mail.app prefs window just for reference it was in png format

I tried the process referred to in the link provided but still no “manage Plug-In’s” button - one thing to note I have GpG mail installed which adds an extra search option to the bottom of the dialog. See jpeg snapshot below

**Comment by apparition47** [comment]
Sorry, still can't see your screenshots. Attaching images through email replies to GitHub doesn't work I guess.

In any case, could you please try [GpG's other suggestion of deleting the DataVaults dir](https://gpgtools.tenderapp.com/kb/gpg-mail-faq/gpg-mail-not-in-manage-plug-ins-list-after-installation-or-doesnt-remain-active)?

**Comment by webdeck** [comment]
I'm on macOS 11.2.2 and didn't have the Manage Plugin-ins... button in my preferences window.  I quit Mail, ran these two commands, then reopened Mail and it worked.  I had used the brew install method and had Mail quit before running brew.

`sudo defaults write “/Library/Preferences/com.apple.mail” EnableBundles 1
defaults write com.apple.mail EnableBundles -bool true`

**Comment by GreenOnRed** [comment]
I get the same issue. Mail 11.5 on High Sierra (10.13.6).
No "manage plugins" button even after following the steps above (command line).
Now Mail doesn't tell me, at its opening, that it disables the uncompatible plugin. That's better. But it won't work...

**Comment by apparition47** [comment]
@webdeck Do you remember if Mail was exited during the installation process? The installation script is supposed to quit Mail then run that EnableBundles command.

@GreenOnRed Others are having this issue as well but I need more info. Could you please open Console.app filtering by "mailtrackerblocker", open Mail, enable the plugin then sending me the logs that appear? 

![](https://user-images.githubusercontent.com/3298414/102243883-05ef7200-3f3f-11eb-9509-f399c84c4dcb.jpg)

**Comment by GreenOnRed** [comment]
@apparition47 :
I do not have the "incompatible plugin" message anymore, but still don't have any "manage plugin" button in the "preferences" window.
And the console.app seems to tell me that's it works... (see the screenshot). However, it doesn't seem to filter the images.
![Capture d’écran 2021-02-27 à 15 04 50](https://user-images.githubusercontent.com/67392795/109389554-45f2ae00-790d-11eb-891b-eb726ceed1c1.png)

**Comment by apparition47** [comment]
@GreenOnRed That's odd, sounds like it's enabled? Are you seeing this blue (or sometimes grey) `ⓧ` icon? If so, it's working. You shouldn't see normal images removed from your emails. It removes small 1x1 images that track you.

![](https://images.ifun.de/wp-content/uploads/2021/02/tracking-blocker-kreis.jpg)

**Comment by GreenOnRed** [comment]
@apparition47 👍 Yes, perfect, I have the blue cross icon! Sorry, yes, I was thinking of any images because I unchecked the Mail filter and made a confusion.
I don't have the button in the menu, but it seems to work. I don't know why I had the error message at the beginning, but it seems to be OK now. Thank you so much!

**Comment by webdeck** [comment]
> @webdeck Do you remember if Mail was exited during the installation process? The installation script is supposed to quit Mail then run that EnableBundles command.

I had manually quit Mail before running the brew install.  After the install completed, Mail opened automatically and there was no Manage Plug-ins button.  I manually quit Mail again, ran the two defaults commands, and launched Mail, which fixed it.

**Comment by apparition47** [comment]
May have a fix in 0.3.13. Please try it out and reopen this ticket if it didn't work (sadly unable to reproduce this issue on any of my Macs).
