### ISSUE TITLE
Tracker Report page not viewable

### ISSUE THREAD

**Issue by colvacdir** [apparition47/MailTrackerBlocker#126]
Ever since the release of version 0.4.x I have been unable to see the Tracker Report page/popup.

Process to see the error: First click on the "x" within an email, and then click on "i". The screen flashes and (I believe) the report flashes for a split second, but you're never able to view it.

MacOS: 10.12.6
Mail: 10.3
Versions Tested : 0.4.1-0.4.4

I'm happy to do any additional tests or provide more details if needed. In the mean time, I'm sticking to 0.3.29.

**Comment by apparition47** [comment]
Thanks for reporting this. Looked like a UI issue. Resolved in 0.4.5.
