### ISSUE TITLE
Unidentified tracker detected in NYTimes email

### ISSUE THREAD

**Issue by j-f1** [apparition47/MailTrackerBlocker#129]
Here’s the email:

[Hear Eric Adams on what’s next for New York (and all cities)..eml.txt](https://github.com/apparition47/MailTrackerBlocker/files/6987187/Hear.Eric.Adams.on.what.s.next.for.New.York.and.all.cities.eml.txt)

**Comment by apparition47** [comment]
Appreciated as always. Fixed in 0.4.8
