### ISSUE TITLE
MTB breaks payment links in Square Up invoices

### ISSUE THREAD

**Issue by humanator** [apparition47/MailTrackerBlocker#130]
I just ran into an issue where i was unable to access an invoice because MTB was stripping out part of the link. The original link without the specific payment details looks like this:

`https://wcssssxs.r.us-west-2.awstrack.me/L0/https:%2F%2Fsquareup.com%2Fpay-invoice%2Finv:`

MTB is removing "awstrack.me" from the link so that it looks like this and no longer works:

`https://wcssssxs.r.us-west-2./L0/https:%2F%2Fsquareup.com%2Fpay-invoice%2Finv:`

**Comment by apparition47** [comment]
Which version of MailTrackerBlocker are you on? This should've been fixed as of 0.3.26 (see #92).

**Comment by humanator** [comment]
I'm not sure what version I had but installing that latest release fixes the problem. Thanks!

**Comment by apparition47** [comment]
@humanator Thanks for the support <3

Also be sure to check out the **Tracker Report** (click the `ⓧ` then `ℹ️`) on the latest version!
