### ISSUE TITLE
Unidentified Tracker collection 1

### ISSUE THREAD

**Issue by m-schmitt** [apparition47/MailTrackerBlocker#133]
I sent a collection of emails with unidentified trackers:

- USPS Informed Delivery
- Experian ProtectMyId
- Dyson
- AAA Crossroads
- Fidelity alert
- InTouch Credit Union
- Citi

**Comment by apparition47** [comment]
Fidelity one seems to be a false positive. The rest have something. Will add in the next update, thanks!
