### ISSUE TITLE
RFE: Way to disable MailTrackerBlocker on a message

### ISSUE THREAD

**Issue by m-schmitt** [apparition47/MailTrackerBlocker#138]
Sometimes an email has broken image links or other issues. This can be due to a problem with MTB, or it can be a some other problem that isn't related to MTB at all.

I'd like for a way to disable MTB on an email, without having to disable the plugin and restart mail.

For this purpose, I don't have any other requirements, which means...

- It would be OK if the switch just disables MTB globally, without restarting Mail
- It would be OK if the disablement is temporary or permanent on the email
- It doesn't need to disable future emails from same sender
- It is OK if all it does is open the mail in a window with MTB disabled
- It is OK if the disablement is so temporary that when you redisplay the email (e.g. change selection to another message and back) MTB is back in force
- It is OK that due to the disablement, any trackers in the email will actually fulfill their tracking purpose

However, other people may have a disablement wishlist with more requirements.

**Comment by apparition47** [comment]
>Sometimes an email has broken image links or other issues.

Curious, is this still a common occurrence? Thought we nailed most of those broken images?

**Comment by m-schmitt** [comment]
> > Sometimes an email has broken image links or other issues.
> 
> Curious, is this still a common occurrence? Thought we nailed most of those broken images?

Right now the broken image links are not due to MTB.

**Comment by erieselbach** [comment]
I have this issue with links that come from MailChimp and perhaps other mailing software. For example my company newsletter has links of the form <https://ndbooks.us8.list-manage.com/track/click?u=94060051763b502e547df0464&id=20cb1689e2&e=8e4145b7c5>. When I click them with MTB enabled, the address is truncated after "us8." and I get a "server cannot be found" message. When I disable MTB, the links open normally. I get this with emails from Wirecutter and a few other sites as well.''

It would be great to disable MTB either for an individual message or to add a whitelist of senders.

<img width="608" alt="Screen Shot 2021-12-13 at 14 02 58" src="https://user-images.githubusercontent.com/65609699/145874419-aac51831-bb6a-4660-8a79-a4584bf03577.png">

**Comment by apparition47** [comment]
@erieselbach That shouldn't be happening since there's MTB doesn't change anything on links (it used to) nor does it match any rule. Which version are you on? If you're already on the latest (0.5.5), could you share the entire email?

**Comment by erieselbach** [comment]
That seems to be the issue. I uninstalled it and reinstalled the latest, and now my links are linking correctly. When I uninstalled I got the message "Purging files for version 0.3.14 of Cask mailtrackerblocker."

Thanks for your help!

**Comment by edmechem** [comment]
> I'd like for a way to disable MTB on an email, without having to disable the plugin and restart mail.
> For this purpose, I don't have any other requirements, which means...
>     * It would be OK if the switch just disables MTB globally, without restarting Mail
>     * It would be OK if the disablement is temporary or permanent on the email
>     * It doesn't need to disable future emails from same sender
>     * It is OK if all it does is open the mail in a window with MTB disabled
>     * It is OK if the disablement is so temporary that when you redisplay the email (e.g. change selection to another message and back) MTB is back in force
>     * It is OK that due to the disablement, any trackers in the email will actually fulfill their tracking purpose

I too would like this capability. But for a different reason – some email lists do that thing of "are you still reading these? we'll unsubscribe you if not..." – so, in that case I'd like to disable the tracker, to let them know that, "Yes, I'm reading this."

It would be great if it were a simple command in MTB's "..." (well, vertical dots) menu, so I could invoke it easily & drive that via the keyboard (via Keyboard Maestro + UI Scripting).

Thanks 🙂

**Comment by apparition47** [comment]
I've added this feature. It will appear in the next release as a toggle on the popover.

<img width="367" alt="Screen Shot 2022-07-02 at 10 21 06 PM" src="https://user-images.githubusercontent.com/3298414/177002618-1992386c-5a0a-4d06-b93e-8249fb2f32b3.png">

- Decided to have it always be on by default.
- Disabling is temporarily until you switch to the next email.
