### ISSUE TITLE
Monterey Support

### ISSUE THREAD

**Issue by ackerthehacker2** [apparition47/MailTrackerBlocker#144]
The plugin doesn't load into Monterey  as expected.

**Comment by apparition47** [comment]
Thanks all for your input. Released 0.5.0 with Monterey support.

**Comment by octothorpe8** [comment]
> For me Monterey always tells me that “My network preferences prevent content from loading privately”. With no hint about what in my network preferences are the issue. So Monterey’s protections don’t help me at all - I miss MailTrackerBlocker!
> […](#)

Just here to echo this. I enabled Monterey Mail's "Protect Mail Activity" right away, but after a few weeks it just stopped working with the same message -- leaving me just loading the images anyway, but without the benefit of trackers being blocked. So, I just reinstalled MailTrackerBlocker even though it technically shouldn't be necessary.
