### ISSUE TITLE
Broken image links on Staples email

### ISSUE THREAD

**Issue by m-schmitt** [apparition47/MailTrackerBlocker#148]
I sent a email from Staples where MTB 0.5.0 says it is blocking a tracker from SendGrid, but the impact is that most of the email does not render.

**Comment by apparition47** [comment]
Thanks, this warrants an update.

The email itself is quite nasty. There's 9 trackers in it from 3 different vendors (Optimove, Litmus, and another unknown one). 3 of the 9 weren't caught in 0.5.0. I guess I'll need to start showing the names of all trackers instead of just the first one.
