### ISSUE TITLE
Trackers without width or height properties defined in the <img /> element

### ISSUE THREAD

**Issue by oneofthedamons** [apparition47/MailTrackerBlocker#150]
I emailed you a sample of one of these:

`<IMG alt="" hspace="0" border="0" src="https://example.org/smtp.mailopen?id=21835077" />`

(I redacted the domain with example.org)

Pretty sure it's a tracker as it has what appears to be a unique identifier and returns a GIF image 1 px x 1 px. However, neither the width nor height properties of the `<img />` element are defined.

Is this a way for trackers to get around the heuristic for identifying them?

**Comment by apparition47** [comment]
Yep. These ones are a bit trickier.

I spotted a similar link in this [mail of this mailing list](https://hunter.listserv.cuny.edu/Scripts/wa-hc.exe?A2=PREMEDINFO-L;59e1f641.1710C&FT=&P=T&H=&S=). The thing these sites have in common is that they're run on this site called `Blackbaud`. So going to list it under there for now.

Thanks!
