### ISSUE TITLE
Ashby unidentified tracker

### ISSUE THREAD

**Issue by austinhuang0131** [apparition47/MailTrackerBlocker#154]
Solid gray. Since they sent me a plain email, I was able to identify the sole remote resource as tracker (so I'll forgo the .eml this time):

```
<img src=3D"https://app.ashbyhq.com/api/beacon/email-read/cea59106-af7f-4db4-8f69-f2902c3c7f9f" height=3D"1" width=3D"1" style=3D"display:none">
```

Btw:

1. It's recruiter spam, and I have told the offending party to stop the trackers.
2. For their tracking links, e.g. https://app.ashbyhq.com/api/beacon/click-redirect/d604409c-9fff-4d18-b67e-84185995f3f1?r=aHR0cHM6Ly9wdWxsZXkuY29t should point to https://pulley.com/ which is the [Base64 decryption](https://toolbox.snopyta.org/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true)&input=YUhSMGNITTZMeTl3ZFd4c1pYa3VZMjl0) of the `r` query string. (Yes, I'm naming them)

**Comment by austinhuang0131** [comment]
Another one (irrelevant), also solid gray; this is the only `img` tracker in the email:

```
<img src=3D'https://link.datacandy.com/i/443/89c93571324bae36fa10d879299f6ffa67371a276aaa0647' height=3D'1' width=3D'1' align=3D'right' />
```

**Comment by apparition47** [comment]
Captured both, thanks!

Going to file point 2 under #112
