### ISSUE TITLE
Please Support Mail 15.0

### ISSUE THREAD

**Issue by malwcal** [apparition47/MailTrackerBlocker#156]
Would it be possible to add support for Mail 15.0 (as included in the betas for MacOS 12.1)?

IMHO MailTrackerBlocker is a better solution than apple's own in build solutions.  Particularly as apple's own technology will not work for me (It says your network preferences prevent content from loading privately - but its too polite to explain why, or what in my "preferences" is preventing it!).

**Comment by berkue** [comment]
Until 12.1 beta 3 the plugin works, but not for beta 4 now!

Yes, also my wish!! Definitely the better solution!
Thanks!

**Comment by ackerthehacker2** [comment]
6FF8B077-81FA-45A4-BD57-17CDE79F13A5

**Comment by apparition47** [comment]
Thanks. Looks like Apple went back to changing the ID on every minor update (on Big Sur, they kept the same ID from 11.0 to 11.6). Will push out an update soon.

**Comment by berkue** [comment]
Same UUID in Release Candidate from yesterday!

**Comment by apparition47** [comment]
Should work on 0.5.5. Let me know if you still see an issue.

**Comment by ackerthehacker2** [comment]
It loads fine

**Comment by apparition47** [comment]
Thanks for verifying @ackerthehacker2

**Comment by apparition47** [comment]
Probably will need to do this song and dance again for 12.2, 12.3, etc

**Comment by berkue** [comment]
Yep! Works fine with 12.1 RC !

Thank You!!

> Am 08.12.2021 um 14:20 schrieb ackerthehacker2 ***@***.***>:
> 
> 
> It loads fine
>

**Comment by malwcal** [comment]
Works here too.  Thanks again!
