### ISSUE TITLE
Cyberimpact uncaught tracker & Veribase unidentified tracker

### ISSUE THREAD

**Issue by austinhuang0131** [apparition47/MailTrackerBlocker#158]
## Cyberimpact

Empty (not caught). Sneaky since they use an actual footer for tracking...

![Screen Shot 2021-12-17 at 14 41 50](https://user-images.githubusercontent.com/16656689/146599200-c45dd1a8-ca9d-4b93-aac5-a836c1412284.png)

```
<img src=3D"https://app.cyberimpact.com/footer-image?ct=3DAKQY7SJ0_vkBuJ7s3yP3QECrA0Pr0rScEGeIkAH_LSatIq4aPWZmFLfGEAPqjEqOaaIZuVZQxmj1c_3FMt2aD9OKiJtd_pGQClbqFgFOano~" alt=3D"Try Cyberimpact for free" width=3D"174" height=3D"37" style=3D"border:0;" class=3D"noresize"/>
```

The `ct` query is different in each email.

## Veribase

Solid gray.

```
<img border="0" width="1" height="1" src="https://e.varibase.com/mail/MOS?uid=131522155&mid=-337258224&dcbid=" /><br />
```

---

p.s. https://www.cyberimpact.com/en/apple-and-privacy-protection-you-wont-know-if-your-subscribers-open-your-emails-anymore/

**Comment by apparition47** [comment]
Got it, thanks!

And read your link--sounds like good news to me.
