### ISSUE TITLE
Updating + new blocking rule

### ISSUE THREAD

**Issue by nevrozel** [apparition47/MailTrackerBlocker#16]
Hi, i installed your plugin via the installer. Is there a way to have it up to date without manually checking and installing the plugin from your webpage?

Also, maybe you can have a look at Mailbutler plugin that installs tracking pixel? Maybe you can try and block it as well. It's quite a popular plugin on the Mac.

https://www.mailbutler.io

Thanks and keep up the great work.

**Comment by apparition47** [comment]
>Also, maybe you can have a look at Mailbutler plugin that installs tracking pixel?

Thanks, Mailbutler will be included in the next update.

>Is there a way to have it up to date without manually checking and installing the plugin from your webpage?

The plugin doesn't have any internal update mechanism at the moment but if you install via brew cask, you can do this to see if you need to update:

```bash
$ brew outdated --cask
mailtrackerblocker (0.3.5) != 0.3.10
```

And this to update:

```bash
$ brew upgrade --cask
```

**Comment by apparition47** [comment]
Leaving this ticket open as a feature request for auto updating. Had a few requests for this before too.

**Comment by nevrozel** [comment]
It would be great to have an auto update feature built in as I see you are actively developing this plugin.

**Comment by andrewcanion** [comment]
I'm trying to upgrade via brew but it's not pulling 0.3.12 which I believe is the latest version. It's seeing 0.3.11 as the latest.

**Comment by apparition47** [comment]
@andrewcanion Live now. Forgot to update the brew appcast 😅

**Comment by apparition47** [comment]
Update check now in 0.4.1
