### ISSUE TITLE
An error has occured: The file “MailTrackerBlocker.pkg” couldn’t be opened.

### ISSUE THREAD

**Issue by Bob16180** [apparition47/MailTrackerBlocker#162]
![error](https://user-images.githubusercontent.com/97044733/147954858-5809946f-8413-430a-8d35-bebf8f5051d9.jpg)
When manually checking for an update I receive an error "An error has occured: The file “MailTrackerBlocker.pkg” couldn’t be opened."
macOS 10.15.7 (19H1615)

**Comment by apparition47** [comment]
Thanks for pointing this out. I fixed this error. (I tried to push out an update but it failed.) I'll try pushing out the update again this week
