### ISSUE TITLE
Does not work with  macOS 12.3 Beta (21E5196i) Mail Version 16.0 (3696.80.61.1.1)

### ISSUE THREAD

**Issue by malwcal** [apparition47/MailTrackerBlocker#165]
As happens from time to time MailTrackerBlocker is incompatible after an upgrade to a new beta OS.

MailTrackerBlocker is still the best way to block trackers - the inbuilt private relay stuff does not work in my environment due to _something_ in my network settings.  Something Apple is too polite to mention.

**Comment by apparition47** [comment]
Could you provide this value from 12.3?

```bash
defaults read /System/Applications/Mail.app/Contents/Info.plist PluginCompatibilityUUID
```

**Comment by malwcal** [comment]
Of course!

$ defaults read /System/Applications/Mail.app/Contents/Info.plist PluginCompatibilityUUID
A4B49485-0377-4FAB-8D8E-E3B8018CFC21

**Comment by apparition47** [comment]
Try 0.5.8

**Comment by malwcal** [comment]
Confirmed working.  Thanks!

**Comment by oneofthedamons** [comment]
> the inbuilt private relay stuff does not work in my environment due to something in my network settings

Possibly of assistance: https://developer.apple.com/support/prepare-your-network-for-icloud-private-relay/
