### ISSUE TITLE
REI Gearmail does not display contents

### ISSUE THREAD

**Issue by spalmen** [apparition47/MailTrackerBlocker#167]
When MTB is enabled, REI Gearmail (marketing) emails do not display, i.e. body content appears completely blank. MTB reports it blocks an Oracle tracker. 

Workaround: Disable MTB and relaunch Mail.

I've attached a .txt of the raw (html) source of a recent Gearmail, and a .pdf of what it looks like when MTB is disabled. If you look into this issue, I'm happy to provide any info you require. Cheers...

[REI Gearmail.txt](https://github.com/apparition47/MailTrackerBlocker/files/8011253/REI.Gearmail.txt)
[REI Gearmail.pdf](https://github.com/apparition47/MailTrackerBlocker/files/8011265/REI.Gearmail.pdf)
.

**Comment by apparition47** [comment]
Ah sorry about that; Trying to avoid these "blank" email issues. I'll post an update soon.

P.S. this email has the most trackers I've seen yet in a single email!
