### ISSUE TITLE
Dismiss tracker info message without click

### ISSUE THREAD

**Issue by martinh2011** [apparition47/MailTrackerBlocker#17]
Suggestion: It would be nice if the info message which is displayed when clicking on the X would work like the tracker information in Safari, i.e. the window would open right below the X when clicked and vanishes as soon as I click elsewhere.

**Comment by apparition47** [comment]
<img width="331" alt="Screen Shot 2021-02-26 at 9 47 50 AM" src="https://user-images.githubusercontent.com/3298414/109238907-b15a5400-7817-11eb-98db-4724d2c78978.png">
A popover like this right? I like that.

**Comment by martinh2011** [comment]
Yes, exactly 👍

**Comment by apparition47** [comment]
Implemented in 0.4.1
