### ISSUE TITLE
Won't work with Mail in macOS 12.5 b1

### ISSUE THREAD

**Issue by berkue** [apparition47/MailTrackerBlocker#171]
Hi,
could you please update the plugin for mail Version 16.0 (3696.100.31)

UUID is the same as in 12.4:  A4B49485-0377-4FAB-8D8E-E3B8018CFC21

Thanks a lot!

Bernd

**Comment by apparition47** [comment]
Thanks for providing the UUID (hope it doesn't change)! Released 0.6.5.
