### ISSUE TITLE
Broken image link from Citi cards

### ISSUE THREAD

**Issue by m-schmitt** [apparition47/MailTrackerBlocker#172]
I sent in an email from the NTB store card which isn't loading the images, using 0.6.5.

**Comment by apparition47** [comment]
Had a look at your email. It's working as intended. The promo images in that email are tracked and have unique identifiers including your first name encoded in the image URL--yikes. But I should ask: did you want it to load those images?

**Comment by apparition47** [comment]
Maybe a good workaround is #138 but I agree that MailTrackerBlocker should be simple to use as its always been. I'll reverse that rule for now until I think of a more elegant solution.

>But I wonder how Monterey's Mail Privacy Protection would handle it?
>
>If a large base of mail-tracker-blockers allows this kind of tracking to slip through, it would encourage the companies to use this method. On the other hand, if a large base of mail-tracker-blockers doesn't permit this, then the companies would know they can't use this method.

Monterey Mail Protection loads all images through a proxy so any data points gleaned from the reader's IP address is unreliable to the marketer. I don't think MailTrackerBlocker itself has enough of a user base to steer marketers away from image-based tracking. But Apple may have enough users starting to use this function as a deterrent ([DHH has a good piece about this point](https://world.hey.com/dhh/email-spy-pixels-are-dead-now-that-apple-will-follow-hey-eb66b759)).

**Comment by apparition47** [comment]
Let's avoid breaking key email images for now. Going to revert that rule in that email for next release
