### ISSUE TITLE
How can I uninstall it when I have macOS 13

### ISSUE THREAD

**Issue by kubai087** [apparition47/MailTrackerBlocker#173]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/68949228/172305886-33c719ec-f4f7-4a47-92e9-ce029241ea3f.png">
 When I got macOS 13, the plugin dose not work well with the mail app and cause this every time. I try to uninstall the plugin but it says the plugin is  uninstalled. How can I do?
<img width="487" alt="Snipaste_2022-06-07_13-54-24" src="https://user-images.githubusercontent.com/68949228/172306007-3840f096-29ff-4ed2-b65c-9cdfcf44d89d.png">

**Comment by apparition47** [comment]
Wow, fast on that 13 beta. Have you tried the [manual uninstallation instructions](https://github.com/apparition47/MailTrackerBlocker#to-uninstall)?

Will have to investigate the new macOS 13 at some point

**Comment by kubai087** [comment]
> 

It works, thanks!
