### ISSUE TITLE
Doesn't work on Big Sur 11.6.7

### ISSUE THREAD

**Issue by edmechem** [apparition47/MailTrackerBlocker#175]
There's a new Mail app (Version 14.0 (3654.120.0.1.13)) that comes with the Big Sur 11.6.7 update, and MailTrackerBlocker now doesn't work anymore.

I tried the trick of adding the new PluginCompatibilityUUID ( D985F0E4-3BBC-4B95-BBA1-12056AC4A531 ) from new Mail.app's Info.plist, and adding it to the bottom of the list of SupportedPluginCompatibilityUUIDs in MailTrackerBlocker.bundle's Info.plist, as well as deleting the ~/Library/Application Support/Mail/Plug-ins directory, to remove old cached plug-in versions.

Seems it's something not just limited to MailTrackerBlocker, but perhaps to all Mail.app plugins, since MsgFilerEngine.bundle is now similarly broken.

Hope it's an easy fix, and curious to know what it is. Thx.

**Comment by apparition47** [comment]
I'm on 11.6.7 and it works for me. [That PluginCompatibilityUUID is already included](https://github.com/apparition47/MailTrackerBlocker/blob/main/Resources/Info.plist#L78) and hasn't changed in a while. What's the exact error message you're seeing? And which version of MailTrackerBlocker are you on? Try the latest (0.6.5).

>Why am I getting a "Incompatible Plug-ins Disabled" message after enabling?

Or if you're seeing this, [see the README](https://github.com/apparition47/MailTrackerBlocker#why-am-i-getting-a-incompatible-plug-ins-disabled-message-after-enabling) for a fix

**Comment by edmechem** [comment]
Huh!  Well. Ok then.   A restart of the computer, and re-install of the plugin - and it's working again! Whew 😅  Sometimes you just need reassurance that it *should* be working. 🤷‍♂️  All's well that ends well. Thx.
