### ISSUE TITLE
double installation

### ISSUE THREAD

**Issue by core-code** [apparition47/MailTrackerBlocker#176]
sorry for the stupid "issue" but it seems after installing MailTrackerBlocker we end up with two installed copies:

```
/Library/Mail/Bundles/MailTrackerBlocker.mailbundle
~/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle 
```

which one is the actually required one? would installing just one single copy suffice?

**Comment by apparition47** [comment]
Mail keeps all available plugins in either `/Library/Mail/Bundles` **(global plugins dir)** or `~/Library/Mail/Bundles` **(user plugins dir)** then copies it to `~/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/` **(enabled plugins dir)** when you enable any given plugin.

Unfortunately, you need to keep both copies as Mail will check if the copies match on startup--I think for plugin update purposes.

**Comment by apparition47** [comment]
Good observation. Yes, the installer moves it to `~/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/` to ensure that the plugin is automatically enabled for the user's convenience on macOS 11 and up.
