### ISSUE TITLE
Tracker using deprecated, non-standard <bgsound> element?

### ISSUE THREAD

**Issue by oneofthedamons** [apparition47/MailTrackerBlocker#179]
I will send an email with an unrecognised tracker, but of interest to me is the use of a <bgsound> element! I had to [look it up](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bgsound) (my web coding days are well and truly behind me): 

```
        <span >
            <img src="https://[REDACTED].[REDACTED].ezyvet.com/email_open_log.php?comid=270448&time=1657006209"
                 style="border:none;width:1px;height:1px;outline: none;"/>
            <bgsound src="https://[REDACTED].[REDACTED].ezyvet.com/email_open_log.php?comid=270448&time=1657006209" volume="-10000"/>
        </span>
```

So we're trying to include ultra-quiet background sounds as mail trackers now, are we? Presumably they think to get around the <img> element being filtered? But looks like it's not supported by modern browsers anyway, so why bother?

Thoughts?

**Comment by apparition47** [comment]
Also captured the tracker in the email, thanks for your submission!
