### ISSUE TITLE
“Ok” should be “OK"

### ISSUE THREAD

**Issue by gruber** [apparition47/MailTrackerBlocker#18]
The alert when you click the ⓧ  button has a button labeled “Ok” with a lowercase k. That’s incorrect — it should always be spelled “OK”, per Apple’s Style Guide:

https://help.apple.com/applestyleguide/#/apsg9a401e4f

<img width="466" alt="image" src="https://user-images.githubusercontent.com/12223/109250317-76c0cf00-77b7-11eb-83e2-696f0d11d77b.png">

**Comment by apparition47** [comment]
TIL; I've been wondering about this for a long time now.

Thanks @gruber! (I'm a regular DF reader too btw--great stuff.)
