### ISSUE TITLE
2x2 px tracker, are they trying to game the (0|1)px tracker detection?

### ISSUE THREAD

**Issue by oneofthedamons** [apparition47/MailTrackerBlocker#180]
Will email the whole email. Looks like a tracking pixel, quacks like a tracking pixel, but is actually a 2x2 grid of tracking pixels?
```
<img src=3D"https://link.mypetwarehouse.com.au/mo/2vhXSRX3LE_872477014_2385=
754_337069_3077279.gif" height=3D"2" width=3D"2" border=3D"0" alt=3D""></bo=
dy>
```

**Comment by apparition47** [comment]
Looks like Emarsys (SAP). First time seeing this. Yikes, will need to make some adjustments.

**Comment by apparition47** [comment]
Added a URL rule for this one but a bit reluctant to expand the generic rule to 2x2px unless there are others out there. Will have to keep an eye out for more 2x2px trackers.
