### ISSUE TITLE
Crashing w/ 0.7.6 Nitty Gritty & Mac Mail 16.0 on Monterey 12.6

### ISSUE THREAD

**Issue by SemoTech** [apparition47/MailTrackerBlocker#188]
Running Mac Mail Version 16.0 (3696.120.41.1.1) on Monterey 12.6 and using MailTrackerBlocker v0.7.6 Nitty Gritty.
No other plugins are in use.

My mail app crashes almost like clockwork daily until I disable the MTB plugin, and then it's rock solid.  Any way to fix?

Thank you.

**Comment by apparition47** [comment]
I'm running the exact some setup without issue.

Could you post the crash report? You have to hit `Report...` then copy and paste the text under `Problem Details and System Configuration`. Looks like this:

![](https://www.maketecheasier.com/assets/uploads/2018/02/how-to-read-crash-reports-1.png)
![](https://eclecticlightdotcom.files.wordpress.com/2021/12/crashreport1.jpg?w=1024)

**Comment by SemoTech** [comment]
Sorry, I had since removed the plugin since it made my MacOS Mail App unusable.  If at a later time I add back the latest version and it behaves the same way, I will be happy to provide the error/crash log. Thank you.
