### ISSUE TITLE
Not working with MacOS 13.1 Beta, Mail Version 16.0 (3731.300.51)

### ISSUE THREAD

**Issue by malwcal** [apparition47/MailTrackerBlocker#189]
$ defaults read /System/Applications/Mail.app/Contents/Info.plist PluginCompatibilityUUID
890E3F5B-9490-4828-8F3F-B6561E513FCC

**Comment by apparition47** [comment]
Thanks for sharing. Try 0.7.7.

**Comment by spittix** [comment]
Installer is working now with MacOS 13.1 Beta and Mail Version 16.0. A short test with several mails was successful, too.
