### ISSUE TITLE
Plugin not available in Mail's plugin listing

### ISSUE THREAD

**Issue by davidbonnet** [apparition47/MailTrackerBlocker#19]
After installing it:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/297345/109307521-14141580-7841-11eb-9884-00d83dce14fa.png">

Note that I'm running Mail version 14.0 (3654.60.0.2.21) in macOS Big Sur version 11.2.2 (20D80).

Also:
```shell
defaults read "/Library/Preferences/com.apple.mail" EnableBundles
1
```

**Comment by apparition47** [comment]
That's odd.

I'm on the latest 11.2.2 as well just to test; No problems on my end.

Which version of MailTrackerBlocker did you install (latest: 0.3.11)? First time installing or is this an update from an older version? How did you install it (pkg directly or brew)? 

What do you see here?

```shell
ls /Library/Mail/Bundles
ls ~/Library/Mail/Bundles
```

**Comment by davidbonnet** [comment]
First time installing it (I installed the latest version: 

```bash
% ls /Library/Mail/Bundles
MailTrackerBlocker.mailbundle
% ls ~/Library/Mail/Bundles
Antidote - PJ.mailbundle
```

**Comment by davidbonnet** [comment]
Moved `MailTrackerBlocker.mailbundle` to the `~/Library/Mail/Bundles` folder and it worked.
