### ISSUE TITLE
Canary read receipt trackers not blocked

### ISSUE THREAD

**Issue by SocietasEvanescentes** [apparition47/MailTrackerBlocker#192]
read-receipts.canarymail.io

**Comment by apparition47** [comment]
Are you not seeing this blue icon <img width="21" alt="Screenshot 2023-01-12 at 9 22 13 PM" src="https://user-images.githubusercontent.com/3298414/212065315-fba4837c-26cc-499b-bdd4-3d19026fcb34.png"> in any email that you received from Canary?

**Comment by apparition47** [comment]
For that specific email that isn't being blocked, could you send it to me by going to `File > Save As > (eml)` then sending me that file attachment?

**Comment by apparition47** [comment]
Ah that's that same email from earlier. I know I asked about version earlier, but just double checking: you're on `0.7.9`?
