### ISSUE TITLE
postinstall edits (especially for Homebrew)

### ISSUE THREAD

**Issue by toobuntu** [apparition47/MailTrackerBlocker#194]
Hello,

Please consider editing the postinstall script.

1)  [After Installer is launched, a dialog window opens for at least 60 seconds.](https://github.com/apparition47/MailTrackerBlocker/blob/main/Packaging/postinstall#L52-L57) That seems a bit long. Maybe 10 seconds would even be enough, but consider at least bringing it down to 30?

2) It seems that the only need for this is to give Installer permissions in Finder. After the installation is finished, Installer remains open, however. Please consider adding one of the following to the [cleanup section](https://github.com/apparition47/MailTrackerBlocker/blob/main/Packaging/postinstall#L90-L93):

```
pkill -fx /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
```
or
```
killall Installer
```
or
```
osascript -e 'quit app "Installer"'
```
or
```
osascript -e 'tell application "Installer" to quit'
```

They all work, but `pkill` or `killall` are significantly faster.
```
$ function op { open -a /System/Library/CoreServices/Installer.app; sleep 0.1; }
$ op; time pkill -fx /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer; echo

real	0m0.039s
user	0m0.005s
sys	0m0.003s

$ op; time killall Installer; echo

real	0m0.017s
user	0m0.003s
sys	0m0.013s

$ op; time osascript -e 'quit app "Installer"'; echo

real	0m1.269s
user	0m0.035s
sys	0m0.042s

$ op; time osascript -e 'tell application "Installer" to quit'; echo

real	0m1.220s
user	0m0.033s
sys	0m0.037s

$ unset -f -- op;
```

This is similar to what was added to the `postflight` section of the `zoom` cask in Homebrew. I added the `pkill` to ensure the console variant of postinstall is as non-interactive as possible. The goal was to avoid any user intervention if it can reasonably be avoided.

Might be relevant to Issue #106.

Thank you for your consideration.

**Comment by apparition47** [comment]
Just so I understand the issue, you're installing via Homebrew and you're seeing the extra popup shown in #106?

>the console variant of postinstall is as non-interactive as possible. The goal was to avoid any user intervention if it can reasonably be avoided.

I made a fix based on your feedback in #195. This should silence the extra 60s dialog and the Installer.app opening (only needed to foreground Installer.app which isn't present during a CLI install).

**Comment by toobuntu** [comment]
Thank you for your response, and such a rapid one at that. If I read #195 correctly, it looks like the fix will solve the issues I raised. There will still be a dialog for 30s, which is okay, but no more having to quit Installer.app. Thank you.

i honestly don’t remember if I got that Finder window on initial install. It seems vaguely familiar, but I don’t remember. What I’m doing now are upgrades via Homebrew, where I get the dialog and Installer issues mentioned.

**Comment by apparition47** [comment]
I'm not really sure what conditions cause the Finder prompt to come up; sometimes I get prompted, sometimes I don't. I agree it'd be nice to do away with the extra info dialog for update installs. But in the meantime, I'd still like to err on the side of caution just with the info dialog just to keep the user informed about Finder.
