### ISSUE TITLE
Email with all images blocked

### ISSUE THREAD

**Issue by malwcal** [apparition47/MailTrackerBlocker#196]
An email from the local entertainment centre has all images blocked by mail tracker.

I can send the email upon request.

**Comment by apparition47** [comment]
Please do. Also let me know which version you're on.

Email in profile: @apparition47

**Comment by malwcal** [comment]
This has been sent.

Version is 0.7.11

**Comment by apparition47** [comment]
Thanks for contributing. Sending out a new version to fix it.
