### ISSUE TITLE
Please update for Mail Version 16.0 (3731.500.192.1.1) on macOS 13.3 beta 2

### ISSUE THREAD

**Issue by berkue** [apparition47/MailTrackerBlocker#197]
Hi,

new UUID is
890E3F5B-9490-4828-8F3F-B6561E513FCC (for 13.3 beta1)

and

281F8A5C-0AF9-4BE6-8B8A-C0CB9C2068BE

for 13.3 beta 2

for plugIns.

Please update!

Thank You!

**Comment by apparition47** [comment]
Done. Thanks for providing the new UUID!
