### ISSUE TITLE
Feature Request: Update Interface

### ISSUE THREAD

**Issue by bitmanic** [apparition47/MailTrackerBlocker#2]
I'm really loving the functionality of this plugin, but I find the red "stop" emoji a bit too jarring. I've put together a design proposal for the interface that more closely matches the existing Mail.app UI while still making emails with blocked trackers distinct from emails with no trackers found. 

Here's what I'm envisioning:

![proposed UI changes for MailTrackerBlocker](https://user-images.githubusercontent.com/190916/88751912-9ba68280-d193-11ea-82ec-d346b5749fa8.png)

I created the stop icons using SVG, and I'd be more than happy to share them if you're interested in using them. Thanks so much for your hard work on this project!

**Comment by apparition47** [comment]
Thanks!

I knew someone would complain eventually 😅. Your design looks good. If you could share your icons, I'd be happy to implement your design.

**Comment by bitmanic** [comment]
Here's the inactive icon:

```xml
<svg width="12" height="12" viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg">
  <path d="M8.5 0L12 3.5v5L8.5 12h-5L0 8.5v-5L3.5 0h5zm-.417 1L11 3.917v4.166L8.083 11H3.917L1 8.083V3.917L3.917 1h4.166zm-.315 2.525L6 5.293 4.232 3.525l-.707.707L5.293 6 3.525 7.768l.707.707L6 6.707l1.768 1.768.707-.707L6.707 6l1.768-1.768-.707-.707z" fill="#898989" fill-rule="evenodd"/>
</svg>
```

And here's the active icon:

```xml
<svg width="12" height="12" viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg">
  <path d="M8.5 0L12 3.5v5L8.5 12h-5L0 8.5v-5L3.5 0h5zm-.025 2.818L6 5.293 3.525 2.818l-.707.707L5.293 6 2.818 8.475l.707.707L6 6.707l2.475 2.475.707-.707L6.707 6l2.475-2.475-.707-.707z" fill="#007AFF" fill-rule="evenodd"/>
</svg>
```

Those icons are optimized to be displayed at 12px. If you'd like a different size, feel free to ask.

**Comment by apparition47** [comment]
Done.
<img width="210" alt="Screen Shot 2020-07-30 at 22 05 17" src="https://user-images.githubusercontent.com/3298414/88926323-cd613b80-d2b0-11ea-8597-36202e0768c9.png"><img width="332" alt="Screen Shot 2020-07-30 at 22 04 57" src="https://user-images.githubusercontent.com/3298414/88926326-ce926880-d2b0-11ea-80b2-38a226fd7b8a.png">

Thanks a lot for the design--made a huge difference. I've credited you on the README. Hope it's enough.

**Comment by bitmanic** [comment]
Of course. I appreciate the quick turnaround! Can't wait to check it out. Thanks, @apparition47!

**Comment by bitmanic** [comment]
Just a follow up: this looks great. Thank you so much, @apparition47!

**Comment by howdytom** [comment]
Sorry to re-open your feature request. Does MailTrackerBlocker version 0.3.5 still uses the blue icons and tracker counter? On macOS Mojave it always shows a gray icon without the blocked counter.

**Comment by apparition47** [comment]
@howdytom I removed the counter because from the emails I've seen, there isn't usually more than one tracker. The blue icon will appear if I have a matching rule (tap on the icon for more info) which indicates there's definitely a tracker in the email. The grey icon appears if there's no matching rule per se, but something that looks like a tracker (and will be blocked anyway).

If you're seeing a lot of grey icons in your emails, feel free to send me the raw content of your emails by tapping on an email and hitting `⎇⌘U` (View>Message>Raw Source) so I can add additional rules.

**Comment by howdytom** [comment]
Got it. Thanks
