### ISSUE TITLE
MailTrackerBlocker 

### ISSUE THREAD

**Issue by nifa81** [apparition47/MailTrackerBlocker#20]
Hi.

what a great idea to program a blocker to track emails. I hate being tracked! Thank you very much!
I have to admit that I'm NOT a programmer and I'm sorry if I'm bothering you...
I installed homebrew successfully as instructed on https://brew.sh/ . 
In a second step I ran the script you provided: 
$ brew install apparition47/tap/mailtrackerblocker
Unfortunately, I get a "-bash: $: command not found" message. 
I'm pretty sure that I'm doing something wrong - any hint?

Thanks, 
Mark

**Comment by wushujames** [comment]
@nifa81 : There is also an installer at https://apparition47.github.io/MailTrackerBlocker/ that you can download and run. That way, you don't have to use homebrew.

**Comment by apparition47** [comment]
Thanks for the kind words @nifa81.

Just to echo @wushujames: please visit my [public landing page](https://apparition47.github.io/MailTrackerBlocker/). There is a `Download macOS 10.11+` button for a GUI installer. There are also setup instructions on that same page.

Please reopen this if you have any more issues!
