### ISSUE TITLE
Broken under Mac OS Sonoma?

### ISSUE THREAD

**Issue by aorrdalca** [apparition47/MailTrackerBlocker#204]
Package won't ope to install.

**Comment by apparition47** [comment]
Not supported. [Apple has decided to drop plug-ins support for Mail starting with Sonoma](https://www.macrumors.com/2023/06/14/macos-sonoma-drops-legacy-mail-app-plug-ins/) so you won't be able to use MailTrackerBlocker anymore. I am however working on a Mail Extension port of MailTrackerBlocker for future versions of macOS.
