### ISSUE TITLE
MailTrackerBlocker 1.0.6 displays corrupted text in mail messages (apostrophes are changed to "â€™"…)

### ISSUE THREAD

**Issue by odysseus90210** [apparition47/MailTrackerBlocker#205]
**Describe the bug**
When MTB is enabled, apostrophes and quotation marks are not displayed correctly in Mail messages: they appear as "â€™" and "â€œ", respectively. Accents don't appear correctly, either. 

**To Reproduce**
1. Load plugin. Display mail message.

**Expected behavior**
Text should not be modified by MTP

**Logs**
No logs

**Environment (please complete the following information):**
 - OS: Mac OS 14.3.1.
 - Other enabled plugins/extensions: Antidote

**Additional context**

**Comment by apparition47** [comment]
@odysseus90210 moving this issue to the new app repository: https://github.com/apparition47/MailTrackerBlockerApp/issues/5. Also please include the `.eml` if possible (you can also send it directly to my email in my profile @apparition47)
