### ISSUE TITLE
Installation crash through brew on macOS 14.4

### ISSUE THREAD

**Issue by mvshmakov** [apparition47/MailTrackerBlocker#206]
**Describe the bug**
The brew installation fails for the macOS 14.4.

**To Reproduce**
1. Run `brew install --cask mailtrackerblocker`
2. Receive an error

**Expected behavior**
The extension is successfully installed.

**Logs**
<details><summary>When I run `brew install --cask mailtrackerblocker`, I receive the following output</summary>
<p>

```txt
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/449d309087e8ea5e51ea4bf88656fff55ed42dc1/Casks/m/mailtrackerblocker.rb
Already downloaded: /Users/mvshmakov/.cache/brew/downloads/f7bbfe8709069dd5004b5e586d24f9ea7e8e8ca173ff317e1c81586241219d5f--mailtrackerblocker.rb
==> Verifying checksum for 'f7bbfe8709069dd5004b5e586d24f9ea7e8e8ca173ff317e1c81586241219d5f--mailtrackerblocker.rb'
Warning: Cannot verify integrity of 'f7bbfe8709069dd5004b5e586d24f9ea7e8e8ca173ff317e1c81586241219d5f--mailtrackerblocker.rb'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "c236ddd0bd03c20a3c01876ac8b3080f641ffd63ea48724b54b3b75c80769076"
==> Downloading https://github.com/apparition47/MailTrackerBlocker/releases/download/0.8.0/MailTrackerBlocker.pkg
Already downloaded: /Users/mvshmakov/.cache/brew/downloads/cf9a6a3718127c38d3852e6c3bb73c1d28bf131730224389ad8da88e7c769312--MailTrackerBlocker.pkg
==> Verifying checksum for 'cf9a6a3718127c38d3852e6c3bb73c1d28bf131730224389ad8da88e7c769312--MailTrackerBlocker.pkg'
==> Installing Cask mailtrackerblocker
==> Running installer for mailtrackerblocker with sudo; the password may be necessary.
installer: Cannot install on volume / because it is disabled.
installer: The version of macOS is too new.
==> Purging files for version 0.8.0 of Cask mailtrackerblocker
Error: Failure while executing; `/usr/bin/sudo -u root -A -E LOGNAME=mvshmakov USER=mvshmakov USERNAME=mvshmakov -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/mailtrackerblocker/0.8.0/MailTrackerBlocker.pkg -target /` exited with 1. Here's the output:
installer: Cannot install on volume / because it is disabled.
installer: The version of macOS is too new.
```

</p>
</details> 

**Environment**
 - OS: macOS 14.4 (23E214)
 - Other enabled plugins/extensions: none
 
**Additional context**
<details><summary>PKG installation also fails with the following message</summary>
<p>

<img width="610" alt="Screenshot 2024-03-12 at 10 34 45" src="https://github.com/apparition47/MailTrackerBlocker/assets/28868855/2ecdae03-c8a9-4421-8419-c038dc183d11">

</p>
</details>

**Comment by apparition47** [comment]
[Apple has decided to drop plug-ins support for Mail starting with Sonoma](https://www.macrumors.com/2023/06/14/macos-sonoma-drops-legacy-mail-app-plug-ins/) so this plugin won't work.

[The app version](https://github.com/apparition47/MailTrackerBlockerApp) that supports Sonoma is now available however. I recommend trying out the TestFlight version first if you're interested.

**Comment by mvshmakov** [comment]
Beta worked for me, thanks!
