### ISSUE TITLE
Cannot install Plugin

### ISSUE THREAD

**Issue by cdr-chakotay** [apparition47/MailTrackerBlocker#207]
Installer pkg fail because MacOS version is too new:

**To Reproduce**
Run `hombrew install --cask mailtrackerblocker`
or Install the package from GitHub Releases.

**The Error**
Error: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=cdrchakotay USER=cdrchakotay  USERNAME=cdrchakotay  -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/mailtrackerblocker/0.8.0/MailTrackerBlocker.pkg -target /` exited with 1. Here's the output:
installer: Cannot install on volume / because it is disabled.
installer: The version of MacOS is too new.

**Details**
MacOS 14.4.1

**Comment by apparition47** [comment]
Yep, see above--Apple killed mail plugins.
