### ISSUE TITLE
MailTrackerBlocker and GPG Mail Extension do not work together

### ISSUE THREAD

**Issue by uelef** [apparition47/MailTrackerBlocker#209]
**Describe the bug**
If MailTrackerBlocker extension is activated the extension for GPG Mail does not work in Mail (macOS Sonoma 14.5).

**To Reproduce**
Deactivating MailTrackerBlocker let's GPG Mail work again
Activated MailTrackerBlocker extension causes problems with GPG. I see the encryption button in Mail, but it can't be activated. Encrypted e-mails cannot be decrypted. The extension of GPG Mail does not work.

**Environment (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Other enabled plugins/extensions: GPG Mail and SpamSieve (that does work with GPG Mail)

**Additional context**

**Comment by berkue** [comment]
Yes, here is the same situation.

**Comment by apparition47** [comment]
This repo is for the older mail plugin. Moved this to https://github.com/apparition47/MailTrackerBlockerApp/issues/20
