### ISSUE TITLE
Plugin fails for Mail client 12.4 (Mac OS 10.14.6)

### ISSUE THREAD

**Issue by tbabcock123** [apparition47/MailTrackerBlocker#21]
<img width="523" alt="Screen Shot 2021-02-26 at 6 30 41 PM" src="https://user-images.githubusercontent.com/64321808/109373072-ac21f700-7861-11eb-9fa2-00b597f8aeae.png">

<img width="460" alt="Screen Shot 2021-02-26 at 6 30 53 PM" src="https://user-images.githubusercontent.com/64321808/109373087-b93ee600-7861-11eb-8b80-7002c111949d.png">

**Comment by apparition47** [comment]
This is the same issue in #11. Wasn't able to reproduce the issue since I don't have access to a Mojave Mac that was updated from Sierra. Thought the issue was related to the DataVaults dir. Could you please first try [MailSuite's "Instructions for Deleting Mail’s DataVaults folder" instructions](https://smallcubed.com/support/scs/troubleshooting_print).

**Comment by apparition47** [comment]
Received a lot of logs and input from other users about similar issues; please try 0.3.12.

**Comment by tbabcock123** [comment]
nope.



The following does nothing because the plug-in never loads:



Also, the console shows no results for ‘mailtracker’ since the plugin never loads.

Is there anything I can supply you for a plugin that fails to load that might be of help?

-t

**Comment by apparition47** [comment]
@tbabcock123 Could I have you try this beta (unsigned so you'll have to allow it through `Security & Privacy`)
[MailTrackerBlocker-unsigned.pkg.zip](https://github.com/apparition47/MailTrackerBlocker/files/6056320/MailTrackerBlocker-unsigned.pkg.zip)? I think there's issues with the installation script according to logs I've seen from others.

**Comment by apparition47** [comment]
@tbabcock123 Please try the new 0.3.14 release and reopen this ticket if it didn't fix your issue. Thanks for your help!

**Comment by tbabcock123** [comment]
installed successfully.

-t
