### ISSUE TITLE
Email comes through corrupt

### ISSUE THREAD

**Issue by malwcal** [apparition47/MailTrackerBlocker#210]
**Describe the bug**
Some emails appear corrupt

**To Reproduce**
View emails eg from aetm.org

**Environment (please complete the following information):**
 - OS: Macos 15.0.1
 
<img width="989" alt="Screenshot 2024-10-18 at 14 17 02" src="https://github.com/user-attachments/assets/39454adf-ae86-44d8-b893-db0d62b08124">

**Comment by apparition47** [comment]
What version of MTB are you running?

**Comment by malwcal** [comment]
1.1.10 (54)

**Comment by apparition47** [comment]
Wasn't able to reproduce. Could you please give 1.1.11 a try? I fixed a similar issue there.

**Comment by malwcal** [comment]
Hi, looks good with 1.1.11.

Thanks!
