### ISSUE TITLE
Plugin fails for Mail client 13.4

### ISSUE THREAD

**Issue by wjshack** [apparition47/MailTrackerBlocker#22]
Checked and is NOT due to Mail symlink issue

**Comment by apparition47** [comment]
>Mail has disabled the following plug-ins: MailTrackerBlocker.mailbundle
>Contact the makers of these plug-ins for versions that are compatible with Mail 13.4.

"fails"? Is this the message you're seeing after enabling the plugin? Which version did you install (latest: 0.3.14)? 

And if possible, could you open Console.app (filter by: `mailtrackerblocker`), open the plugin, then send me the logs?

![](https://user-images.githubusercontent.com/3298414/102243883-05ef7200-3f3f-11eb-9509-f399c84c4dcb.jpg)

**Comment by MistrMoose** [comment]
I got the same error message in Mail when I installed a few days ago, so I removed the plugin.

I just tried it again today to try to snag a shot of the error dialog, however, and now it's working okay.  Go figure.  This is in fully updated Catalina 10.15.7

**Comment by wjshack** [comment]
I had originally tried to install 0.311 version. Tried 0.314 version this morning and it works.
