### ISSUE TITLE
Fails on macOS Mojave 10.15.7 mail.app 13.4

### ISSUE THREAD

**Issue by thrint-atx** [apparition47/MailTrackerBlocker#25]
So I tried the [mailbundles fix,](https://smallcubed.com/support/scs/troubleshooting_print) where you disable SIP, remove the DataVaults folder and reboot.

After that I check the `mail.app > Preference > General > Manage Plug-ins` and turn on the MailTrackerBlocker plug-in and immediately get the message that it is incompatible with mail 13.4:

<img width="420" alt="Screen Shot 2021-02-27 at 7 49 13 AM" src="https://user-images.githubusercontent.com/79754106/109389354-cabfd680-78d1-11eb-871b-08a6029efb3c.png">

This is a new MacBookPro 16" (i9 , 16GB, 512GB SSD) with the OS that shipped from the factory and my profile (using migration assistant) moved from my previous MacBookPro that was also running Mojave.

**Comment by apparition47** [comment]
Thanks for the report. Seems like this a common theme with OS updates or the migration assistant.

But firstly, could you try this then reopen Mail with the plugin enabled:
```bash
codesign --remove-signature /Library/Mail/Bundles/MailTrackerBlocker.mailbundle
```

If that doesn't work, please open Console.app (filtering by: mailtrackerblocker), then opening Mail with the plugin and send me the logs.

![](https://user-images.githubusercontent.com/3298414/102243883-05ef7200-3f3f-11eb-9509-f399c84c4dcb.jpg)

**Comment by thrint-atx** [comment]
I copied that command from the web page but it returned an error:

`steve@SR-MBP16 ~ % codesign --remove-signature /Library/Mail/Bundles/MailTrackerBlocker.mailbundle
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Library/Mail/Bundles/MailTrackerBlocker.mailbundle: the codesign_allocate helper tool cannot be found or used`

I did that after quitting mail.app.

Then I opened console and did the mail tracker filter, launched Mail and turned on the mailtrackerblocker plug in. And immediately got the error as before. I have attached the relevant log entries from Console.

[MailTrackerLog.txt](https://github.com/apparition47/MailTrackerBlocker/files/6054607/MailTrackerLog.txt)

**Comment by apparition47** [comment]
Another user had this exact issue. Could you please run this in Terminal then run the above again:

```bash
xcode-select --install
```

**Comment by thrint-atx** [comment]
Well whatever that command did, it worked!

I have attached an updated log in case it is helpful

thx!

Steve
[MailTrackerLog2.txt](https://github.com/apparition47/MailTrackerBlocker/files/6054687/MailTrackerLog2.txt)

**Comment by apparition47** [comment]
Thanks for reporting back! Going to put out a hotfix to workaround this issue.
