### ISSUE TITLE
MacOS 11.2 / MailTrackerBlocker doesn't appear in "Manage Plug-ins" list

### ISSUE THREAD

**Issue by Fresnel8** [apparition47/MailTrackerBlocker#27]
Hi,

I follow the steps below:
1. Mails is closed
2. I install MailTrackerBloker trough Terminal/Homebrew => ok
3. In Mail, I open Preferences > General > Manage Plug-ins (Modules in French) and ... nothing! I have no Plug-ins/Modules
4. I attach 2 PNG file
5. Why ? Not english language ?
<img width="762" alt="Capture d’écran, le 2021-02-27 à 13 15 02" src="https://user-images.githubusercontent.com/79763439/109397742-3fad0380-7906-11eb-861e-7d654b81b79e.png">
<img width="766" alt="Capture d’écran, le 2021-02-27 à 13 05 42" src="https://user-images.githubusercontent.com/79763439/109397746-45a2e480-7906-11eb-9d7f-7912266dada0.png">

**Comment by apparition47** [comment]
Hi @Fresnel8 , it's not because of your system language setting. Could you please try the ["Resetting Mail’s Private Plug-Ins Folder - macOS 11" instructions here](https://c-command.com/spamsieve/help/resetting-mail-s-privat)?

**Comment by Fresnel8** [comment]
Unfortunetly, nothing work.
1. I can remove Bundles folder (steps 1 to 4) with Finder (no change) but not in terminal, even with sudo.
2. I apply steps 5 to 9 and repeat steps 2 to 4 => doesn't work
3. I do step 12.

I have Bundles folder at two place: first, in /users/Myusername/Library/Apllication Support/Mail/Plug-ins folder.
If I erase the Bundles folder here, each time I open Mail, a new empty Bundles software is created . This folder is in my library, there is nothing, I understand I cannot see Plug-ins in "manage Plug-ins List"

The second place is /Library/Mail: it is not a folder but an alias and this alias leads to /System/Volumes/Data/MailBundles/Library/Mail/Bundles where I find MailTrackerBlocker.mailbundle.
Maybe there is a problem somewhere :) : which Bundles folder read Mail app for managing Plug-ins...?

**Comment by apparition47** [comment]
>which Bundles folder is Mail app reading for managing Plug-ins...?

My installer puts it into `/Library/Mail/Bundles` for all users. Then Mail itself makes duplicate copies of it when the plugin is enabled:

```bash
# note: Big Sur
$ sudo find / -name MailTrackerBlocker.mailbundle

# installed by my pkg
/Library/Mail/Bundles/MailTrackerBlocker.mailbundle 

# generated by Mail upon enabling
/System/Volumes/Data/Library/Mail/Bundles/MailTrackerBlocker.mailbundle
/System/Volumes/Data/Users/myuser/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle
```

>The second place is /Library/Mail: it is not a folder but an alias

This part seems a little strange. On my Mac, it's not an alias.
```bash
$ ls -ld /Library/Mail/Bundles 
drwxr-xr-x  4 myuser  staff  128 Feb 28 21:33 /Library/Mail/Bundles
```

Maybe try removing this alias entirely, then reinstalling the latest pkg again.

**Comment by charlot777** [comment]
Same problem here but by deleting the second folder (alias) I was able to install the plug-in

**Comment by Fresnel8** [comment]
Yes, it works!
I removed the alias. reinstall => it works.
Thank you very much @apparition47

**Comment by apparition47** [comment]
Awesome! Thanks for reporting back.

A bit concerned a second person here had the same symlink setup. Will have to keep an eye out to see who else has this setup how it was even created in the first place. Closing for now!
