### ISSUE TITLE
Clarify “MailTrackerBlocker blocked a tracker” message

### ISSUE THREAD

**Issue by j-f1** [apparition47/MailTrackerBlocker#29]
Currently, the text displayed when clicking the button when it’s blue is:

> MailTrackerBlocker blocked a tracker from [tracker].
>
> [tracker] can track if you opened this email, when you opened it (and how often), where you are located and how you opened it (phone, computer). Some or all of this data could have been reported back to its sender.";

This gives the impression that MailTrackerBlocker didn't actually do anything. I think it would be more clear if it said “[tracker] would have been able to track…” or something similar to indicate that the attempt to track you was blocked.

**Comment by apparition47** [comment]
The first and last sentences make it pretty clear that an attempt was blocked. But I can see how the middle sentence can be interpreted otherwise. I'll revisit this, thanks

**Comment by j-f1** [comment]
To me, “Some or all of this data could have been reported back to its sender” also implies that the tracker was (or may have been) successful at tracking you.

**Comment by apparition47** [comment]
Shuffled around the text a bit in 0.4.x but the last line will be corrected in the upcoming 0.4.6 release, thanks!
