### ISSUE TITLE
Big Sur support

### ISSUE THREAD

**Issue by NetOperatorWibby** [apparition47/MailTrackerBlocker#3]
<img width="372" alt="SS 2020-07-29 at 12 54 03 AM" src="https://user-images.githubusercontent.com/1288356/88762053-416ed880-d125-11ea-9bc5-5fc490e69f4d.png">

_I'm on the Big Sur beta_

**Comment by apparition47** [comment]
Thanks for reporting--I saw this coming. Unfortunately, I don't currently have access to a machine with Big Sur at the moment; need someone to class-dump the new Mail app frameworks and the new plugin UUID.

I'll try to come around to this.

**Comment by apparition47** [comment]
Doubt this will work but could I ask you to try this? [MailTrackerBlocker-develop.pkg.zip](https://github.com/apparition47/MailTrackerBlocker/files/5002520/MailTrackerBlocker.pkg.zip) (Big Sur beta 3 or newer only)

**Comment by donbachi** [comment]
Hi,
just downloaded your beta-build and can confirm that it's working.

**Comment by NetOperatorWibby** [comment]
@apparition47 YES

Success!

**Comment by apparition47** [comment]
Thanks! Out of curiousity, could I have one of you Big Sur users to get me the value of this?
```
defaults read /System/Applications/Mail.app/Contents/Info.plist PluginCompatibilityUUID
```

**Comment by NetOperatorWibby** [comment]
@apparition47 `6EEA38FB-1A0B-469B-BB35-4C2E0EEA9053`

**Comment by NetOperatorWibby** [comment]
_Figured I'd reopen this until this until you close it_

**Comment by apparition47** [comment]
@NetOperatorWibby Thanks again. Interestingly enough, this UUID is actually the same as 10.15. I'm expecting Apple to change up it up sometime before the Big Sur public release so if possible, please update this thread when you see this issue popup again.

**Comment by NetOperatorWibby** [comment]
Will do!

**Comment by helptiger** [comment]
![Screenshot-31-40-2020_02 40 28](https://user-images.githubusercontent.com/10258902/89035939-16aa9d00-d33c-11ea-9acc-6a45f799438a.png)

It works with Big Sur Beta (3). 
Little cosmetic issues. (visability)

**Comment by Chuby1** [comment]
I have installed your Plugin on a MacBookPro 16 with Catalina 10.15.6. Unfortunatly the Plugin for the "GPG-Tools" does not work anymore now. Received encrypted mails will not be shown decrypted  as long as your plugin is active.
Deactivating your plugin and restarting Apple Mail will make the Plugin for the GPG-Tools working again.
Would be great if you could solve this problem.

kind regards Chuby

**Comment by apparition47** [comment]
@helptiger will fix soon, thanks.

@Chuby1 please open a separate issue--this thread is specifically for Big Sur support. Are the emails being decrypted? Or is it just the indicator in the header that's not right? Also let me know which version of GPGMail you're using.

**Comment by apparition47** [comment]
@helptiger Please try 0.2.5 and let me know if the icon is still running off the header. Thanks a lot!

**Comment by Chuby1** [comment]
Just tried 0.2.5 but it´s the same than before. The GPG-Tools Plugin
is not working…

**Comment by helptiger** [comment]
> @helptiger Please try 0.2.5 and let me know if the icon is still running off the header. Thanks a lot!

good:
![Screenshot-01-41-2020_05 41 09](https://user-images.githubusercontent.com/10258902/89105166-09b2aa00-d41f-11ea-9db6-f2f148cbeba8.png)
a bit out of shape:
![Screenshot-01-42-2020_05 42 59](https://user-images.githubusercontent.com/10258902/89105167-0cad9a80-d41f-11ea-875b-bccdf9297e19.png)

**Comment by helptiger** [comment]
many mails look good, some not yet optimal (If symbols or text is displayed above it) 

![Screenshot-02-52-2020_03 52 58](https://user-images.githubusercontent.com/10258902/89126805-14397600-d4e9-11ea-836e-0df072f43a70.png)

![Screenshot-02-56-2020_05 56 59](https://user-images.githubusercontent.com/10258902/89126925-13551400-d4ea-11ea-8af8-e9a1f68fba47.png)

**Comment by apparition47** [comment]
@helptiger I appreciate your constant feedback. 

I just realized from your screenshots that Apple moved the 🚩 flagged and 📎 attachment icons to right and below the timestamp in Big Sur, unlike before where it was beside the sender field on the left. I may have to find a new place altogether for our button.

**Comment by apparition47** [comment]
>Entfernte Inhalte laden _(Load remote content)_

@helptiger I also have to point out that [disabling "load remote content in messages"](https://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2019/07/mac-load-remote.jpg) is redundant when used with MailTrackerBlocker. This option prevents ALL images (and trackers) from loading but MailTrackerBlocker can also do this without preventing legitimate images from being displayed.

I recommend reenabling this option for the best experience.

**Comment by NetOperatorWibby** [comment]
Oh wow, that's awesome! I can finally view emails as intended (but without trackers).

**Comment by NetOperatorWibby** [comment]
Updated Big Sur again and this broke. However, we have a new value for `PluginCompatibilityUUID`:
`D985F0E4-3BBC-4B95-BBA1-12056AC4A531`.

**Comment by apparition47** [comment]
@NetOperatorWibby Thanks for the UUID for beta 4. Please [see 0.2.8](https://github.com/apparition47/MailTrackerBlocker/releases/tag/0.2.8).

**Comment by NetOperatorWibby** [comment]
New update and the value didn't change but the plugin won't start.

<img width="372" alt="SS 2020-08-23 at 7 27 18 PM" src="https://user-images.githubusercontent.com/1288356/90992635-e84c6600-e565-11ea-909e-7ec5eaf80e27.png">

**Comment by apparition47** [comment]
@NetOperatorWibby Looks like Apple requires signing and notarization as of the latest Bir Sur beta. I never signed before because doing so caused older versions of macOS not to load. I added a part in the installer script to strip out the signature for this case. But hey, we are able to notarize the app now.

Please [checkout 0.3.0](https://github.com/apparition47/MailTrackerBlocker/releases/tag/0.3.0) and let me know if it works for you.

**Comment by NetOperatorWibby** [comment]
It does! Thanks for the quick fix!

**Comment by fKing** [comment]
apparition47, trying to reach you with a proposal (can't find contact info). get back to me, it's a mailbundle issue; was referred to you by https://github.com/bteapot

**Comment by NetOperatorWibby** [comment]
Mail refuses to recognize this plugin as valid on the 11.1 beta (20C5048k). The `PluginCompatibilityUUID` is unchanged.

**Comment by apparition47** [comment]
@NetOperatorWibby Which version of MailTrackerBlocker did you try?

**Comment by NetOperatorWibby** [comment]
@apparition47 I tried the two most recent releases.

**Comment by giuliomagnifico** [comment]
macOS 11.1 with Mail 14.0 is incompatible with this great plugin.

**Comment by apparition47** [comment]
@NetOperatorWibby @giuliomagnifico thanks for the support. Fixed with 0.3.2. Please check the latest `.pkg` from the [Releases page](https://github.com/apparition47/MailTrackerBlocker/releases)

**Comment by colamixer** [comment]
Sorry, it is not working for me!
Tested on 11.0.1 with 0.3.1 and on 11.1 with 0.3.2.
After restarting Mail, it is disabling your plugin!

**Comment by uxusoft** [comment]
> @NetOperatorWibby @giuliomagnifico thanks for the support. Finally got around to installing 11.1 today. Fixed the issue on 0.3.2. Please check the latest `.pkg` from the [Releases page](https://github.com/apparition47/MailTrackerBlocker/releases)

Working OK on BigSur 11.1. After restarting working also ok.

**Comment by apparition47** [comment]
@colamixer The 0.3.2 pkg works for me both on my 11.1 machine and my other 11.0.1 Mac. @uxusoft reported success as well. 

Are you on the public release of 11.1? Are you on Intel or Apple Silicon? Could you share output from the Console.app filtering by "mailtrackerblocker"?

![Console](https://user-images.githubusercontent.com/3298414/102243883-05ef7200-3f3f-11eb-9509-f399c84c4dcb.jpg)

**Comment by colamixer** [comment]
I am on the public release of 11.1 (Apple Silicon, Mac mini).

fehler	18:08:58.997725+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle
fehler	18:08:58.997771+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents
fehler	18:08:58.997803+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/_CodeSignature
fehler	18:08:58.997833+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/_CodeSignature/CodeResources
fehler	18:08:58.997850+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/MacOS
fehler	18:08:58.997876+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/MacOS/MailTrackerBlocker
fehler	18:08:58.997894+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/Resources
fehler	18:08:58.997921+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/Resources/de.lproj
fehler	18:08:58.997948+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/Resources/de.lproj/Localizable.strings
fehler	18:08:58.997965+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/Resources/en.lproj
fehler	18:08:58.997992+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/Resources/en.lproj/Localizable.strings
fehler	18:08:58.998008+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/Resources/fr.lproj
fehler	18:08:58.998034+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/Resources/fr.lproj/Localizable.strings
fehler	18:08:58.998054+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/Resources/inactive.pdf
fehler	18:08:58.998069+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/Resources/possible.pdf
fehler	18:08:58.998085+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/Resources/active.pdf
fehler	18:08:58.998102+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/Info.plist
fehler	18:08:58.998119+0100	kernel	System Policy: Mail(1169) deny(1) file-write-flags /Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/PkgInfo
standard	18:08:59.393575+0100	Mail	NSBundle </Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle> (not yet loaded) failed to load. The error was:
Error Domain=NSCocoaErrorDomain Code=3585 "Das Paket „MailTrackerBlocker“ konnte nicht geladen werden, da es keine Version für die aktuelle Architektur enthält." UserInfo={NSLocalizedFailureReason=Das Paket enthält keine Version für die aktuelle Architektur., NSLocalizedRecoverySuggestion=Versuche, eine Universal-Version des Pakets zu installieren., NSFilePath=/Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/MacOS/MailTrackerBlocker, NSBundlePath=/Users/fk/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/MailTrackerBlocker.mailbundle, NSLocalizedDescription=Das Paket „MailTrackerBlocker“ konnte nicht geladen werden, da es keine Version für die aktuelle Architektur enthält.}

**Comment by apparition47** [comment]
Thanks @colamixer for your report; didn't have the project setup properly. It supports Apple Silicon now! Check the releases page.

>#0.3.3 version
>lipo -archs /Library/Mail/Bundles/MailTrackerBlocker.mailbundle/Contents/MacOS/MailTrackerBlocker
>x86_64 arm64

Closing this thread since Big Sur is public and supported already.
