### ISSUE TITLE
Mail 12.4/MacOS 10.14.6 Not Working After Activating Plug-In

### ISSUE THREAD

**Issue by RuffingIt** [apparition47/MailTrackerBlocker#32]
@RuffingIt Any screenshot? Sounds like your accounts are missing? You can readd all your accounts in `Mail > Preferences > Accounts`

_Originally posted by @apparition47 in https://github.com/apparition47/MailTrackerBlocker/issues/11#issuecomment-787394679_

Just wanted to provide an update on this issue since the previous thread has been closed.

I couldn’t access Preferences from Mail because that option was greyed out:
![Screen Shot 2](https://user-images.githubusercontent.com/79778359/109425040-5c077980-79b4-11eb-912b-48161fc4fc1f.png)

But the accounts were viewable in System Preferences.

Ended up restoring an earlier version of my Mail folder using Time Machine. Still had the same issues.

Then I did these steps that’s been referenced here: https://gpgtools.tenderapp.com/discussions/problems/106098-gpgmailloadermailbundle-incompatible-with-mail-134#comment_48391312

When I restarted Mail, everything was back to normal. I still can’t activate MailTrackerBlocker (after I check it and Mail restarts, it remains unchecked) but at least I have my Mail working again.

**Comment by apparition47** [comment]
@RuffingIt I noticed you closed this issue. Did you manage to solve it?

If you already cleared out your DataVaults as per those instructions, could you try the [latest 0.3.14](https://github.com/apparition47/MailTrackerBlocker/releases/tag/0.3.14)?

**Comment by RuffingIt** [comment]
@apparition47 Thought I had updated this in #11. Yes, I installed 0.3.14 and now it works without a hitch. The only thing I noticed is that when launching Mail there is a slight delay before the Message Viewer window appears.

**Comment by apparition47** [comment]
Happy to hear that!

Which Mac are you on? There's going to be a slight performance hit when running email against the filter list (causing the delay).

**Comment by RuffingIt** [comment]
It a Late 2012 Mac Mini so the performance hit is understandable.
