### ISSUE TITLE
Where is the difference between grey X and blue X?

### ISSUE THREAD

**Issue by eyekey** [apparition47/MailTrackerBlocker#33]
They both report tracking pixels beeing blocked.
So I really ask myself where the difference lays.

**Comment by msridhar** [comment]
You can click on the X to see a message.  I believe blue X corresponds to blocking a known tracker URL, while grey corresponds to blocking tracker-like behavior from some other URL.

**Comment by apparition47** [comment]
@msridhar nailed it. 

1. `blue ⓧ`: blocked & identified a tracker from a known vendor
2. `solid grey ⓧ`: blocked an element that may be a tracker, unknown vendor
3. `grey bordered ⓧ`: no tracker detected

Trying to keep the rule list up-to-date to reduce cases of (2) and false positive cases of (3) so be sure to keep MailTrackerBlocker updated!

**Comment by eyekey** [comment]
Thanks for clarification. 
Maybe you could change "grey bordered" to an "ok" sign? ✓
Or nothing at all?

**Comment by apparition47** [comment]
I have plans to change the UI/icons (also #14) but still thinking about how it should look CC: @bitmanic
