### ISSUE TITLE
After upgrading via Homebrew, plugin is disabled in Mail

### ISSUE THREAD

**Issue by msridhar** [apparition47/MailTrackerBlocker#34]
Thanks for the great tool!  I just used Homebrew to upgrade from version 0.3.11 to 0.3.14.  The upgrade process restarted Mail, but afterward the new version of the plugin was not yet enabled; I had to manually enable it in the Mail preferences again.

Not sure how easy this is to fix, but it'd be great if it were at least documented in the README.

**Comment by apparition47** [comment]
Thanks for pointing that out; will do!

Used to be possible (before SIP became default) to directly dump the mailbundle/plugin into the DataVaults dir to automatically enable it.
