### ISSUE TITLE
Not detecting beacons from wish.com emails.

### ISSUE THREAD

**Issue by larkov** [apparition47/MailTrackerBlocker#38]
Does not detect email beacons sent by wish.com in their emails.

```
<img id="email-beacon" src="http://www.wish.com/email-beacon.png?utm_campaign=2021-02-22_SHIPMENT_CONFIRMATION_<removed>&amp;uuid=<removed>&amp;cmpgnid=2021-02-22_SHIPMENT_CONFIRMATION_<removed>&amp;ee=v1_2LaP22BArxLeSQGig1coHQeyzqYnLareXp7HajXKqjeypKPutzp3H9881Dhaa2rYSNiER7p2dVHA&amp;utm_source=SHIPMENT_CONFIRMATION&amp;template=emails%252Fremix%252Fnotifications%252Ftransaction_item_status_update.html&amp;recvuid=<removed>" height="1px" width="1px" />
```
Removed some ids above.

It seems to track that I've read the shipping status, but I don't care.

**Comment by apparition47** [comment]
Just to double check, are you seeing:

A. <img width="47" alt="Screen Shot 2021-03-01 at 5 48 55 PM" src="https://user-images.githubusercontent.com/3298414/109473233-65790a80-7ab6-11eb-84d5-7265b5c0079a.png"> (no tracker detected) 
or B. <img width="45" alt="Screen Shot 2021-03-01 at 5 48 52 PM" src="https://user-images.githubusercontent.com/3298414/109473255-6ca01880-7ab6-11eb-9c93-7471253497be.png"> (possible tracker detected)?

**Comment by larkov** [comment]
I'm seeing A: No tracker detected and when I click on the mark for information. The dialog is:

<img width="248" alt="image" src="https://user-images.githubusercontent.com/3763465/109473724-faa6df80-7a73-11eb-9205-cb0ba7d30b17.png">

**Comment by apparition47** [comment]
Thanks for your submission, this will be addressed.
