### ISSUE TITLE
Mail 11.5 Support

### ISSUE THREAD

**Issue by nodefive** [apparition47/MailTrackerBlocker#4]
Would be nice to have this on older macOSs.

I can dump if helps to build for this version. Tell me what should I do and what frameworks should I dump.

Thanks in advance.

**Comment by apparition47** [comment]
What macOS is 11.5 on? 10.13 High Sierra? I suspect my plugin might already work as far back as 10.9 as-is but I can't personally verify that. Could you try running the plugin and let me know which error you get? Or is it crashing?

**Comment by nodefive** [comment]
Unfortunately no. When I start Mail, it pops a little window saying:

```
Incompatible Plug-ins Disabled
Mail has disabled the following plug-ins:
	MailTrackerBlocker
Contact the makers of these plug-ins for versions that are compatible with Mail 11.5.
```

Maybe I am doing something wrong. I've downloaded the pkg, installed. I wasn't able to do the XCode step because that `Manage Plug-ins` is not present in XCode 10.1. But the bundle ins present in `/Library/Mail/Bundles`.

**Comment by apparition47** [comment]
Sounds like you're doing everything correctly, thanks.

I can try and add support but it's hard for me to dev/test because I don't have ready access to older OSs. But if you could provide the `headers.zip` from the following, that would be super helpful:

```bash
# download class-dump bin
# feel free to download the dmg off the official site if you don't trust this 3rd party compile
git clone https://github.com/ivRodriguezCA/class-dump-binaries

cd class-dump-binaries
cd binaries
mkdir Headers

# get plugin compat UUID
defaults read /Applications/Mail.app/Contents/Info.plist PluginCompatibilityUUID > Headers/pluginuuid.txt

# dump headers/frameworks
./class-dump -I -H -o "Headers/MailUI" "/Applications/Mail.app/Contents/MacOS/Mail"
./class-dump -I -H -o "Headers/EmailAddressing" "/System/Library/PrivateFrameworks/EmailAddressing.framework/EmailAddressing" 
./class-dump -I -H -o "Headers/MailCore" "/System/Library/PrivateFrameworks/MailCore.framework/MailCore"
./class-dump -I -H -o "Headers/MailUIFW" "/System/Library/PrivateFrameworks/MailUI.framework"
./class-dump -I -H -o "Headers/MailFW" "/System/Library/PrivateFrameworks/Mail.framework"

# zip everything up to send
zip -r -9 headers.zip Headers
```

**Comment by Shmoopi** [comment]
@apparition47 attached are the zipped headers for Mail Version 12.4 (3445.104.15) - macOS 10.14.6.

[headers.zip](https://github.com/apparition47/MailTrackerBlocker/files/5002209/headers.zip)

**Comment by apparition47** [comment]
Doubt this will work but could I ask you to try this? [MailTrackerBlocker-develop.pkg.zip](https://github.com/apparition47/MailTrackerBlocker/files/5002520/MailTrackerBlocker.pkg.zip)

**Comment by Shmoopi** [comment]
@apparition47 that did not work for 12.4 - still claims that it's not compatible with the version.

"Mail has disabled the following plug-ins:

	MailTrackerBlocker.mailbundle

Contact the makers of these plug-ins for versions that are compatible with Mail 12.4."

**Comment by apparition47** [comment]
@Shmoopi @nodefive I think I found the issue. Please try this: [MailTrackerBlocker-beta2.pkg.zip](https://github.com/apparition47/MailTrackerBlocker/files/5005406/MailTrackerBlocker.pkg.zip) (changed min target to 10.11). Thanks for testing.

**Comment by Shmoopi** [comment]
@apparition47 - worked perfectly!  Blocking appears to be working as intended.  Thank you!!

**Comment by apparition47** [comment]
Released 0.2.5 with this baked change baked in. Thanks guys!

**Comment by nodefive** [comment]
> ```shell
> zip -r -9 headers.zip Headers
> ```

High Sierra, Mail 11.5 headers: https://github.com/nodefive/Stuff/blob/master/headers.zip

**Comment by apparition47** [comment]
@nodefive please try out 0.2.5 and reopen this issue if it doesn't work for you

**Comment by nodefive** [comment]
Indeed is now working. Thank you!
