### ISSUE TITLE
Plugins fails to activate : GPGMAIL_MULTIPLE_INSTALLATIONS_TITLE

### ISSUE THREAD

**Issue by w3cdotorg** [apparition47/MailTrackerBlocker#40]
Hello,

After installing via brew and activating the plugin, I have this message when launching Mail.app (14.0, on macOS Big Sur 11.2.2):

<img width="403" alt="Screen Shot 2021-03-01 at 10 29 35 AM" src="https://user-images.githubusercontent.com/19980081/109478265-5031bb00-7a79-11eb-9092-480c6005e3ce.png">

Clicking the button just closes Mail.app. If I delete the Bundle from my /Users/username/Library/Mail/Bundles/ folder, I can launch Mail.app again. The only other Mail plugin I have [is Antidote](https://www.antidote.info). 

I've already removed [GPGTools](https://gpgtools.org) just to check, and the only GPG I have installed is via brew (GPG 2.2.27). I've tried to locate other older installs of gpg, to no avail. Is there something else I can check?

Best

**Comment by apparition47** [comment]
I fixed an issue when using GPGMail a while ago (#6). Plugins are usually user-installed at either: `/Library/Mail/Bundles` or `~/Library/Mail/Bundles`. Did you clear everything out of there? What version of GPGTools were you running?

**Comment by w3cdotorg** [comment]
In `/Library/Mail/Bundles/`, I only have your plugin, and in `~/Library/Mail/Bundles/` (normal user, not an admin) only the Antidote - PJ.mailbundle. If I don't do anything, your plugin doesn't appear in the Manage Plugins list, I have to copy it to `~/Library/Mail/Bundles/`.

I don't remember which version of GPGTools I was using... Should I try reinstalling GPGTools?

**Comment by apparition47** [comment]
Do you still use GPGTools? If not, try [running their uninstaller](https://gpgtools.tenderapp.com/kb/faq/uninstall-gpg-suite). They usually do an update for each major release of macOS so you'll need to update accordingly if you do use it.

**Comment by w3cdotorg** [comment]
Thanks! No, I don't use it any more, but I ran their uninstaller before opening the issue. I also tried to uninstall/reinstall gpg from brew, but it still gives the same error.

**Comment by apparition47** [comment]
Just reread your message above. Looks like your GPGMail is properly removed but you need to delete one of the `MailTrackerBlocker.mailbundle`s that you have. You can only have one in one place (either `/Library/Mail/Bundles` or `~/Library/Mail/Bundles`).

**Comment by w3cdotorg** [comment]
Oh OK! I moved it to `~/Library/Mail/Bundles`. It works perfectly! Thanks.
