### ISSUE TITLE
Wrong alert title?

### ISSUE THREAD

**Issue by larkov** [apparition47/MailTrackerBlocker#42]
https://github.com/apparition47/MailTrackerBlocker/blob/bcdea1de680d2e8ebe5390a57c57bf6b770f29b8/Source/HeaderViewController%2BMailTrackerBlocker.m#L65

Shouldn't that be MailTrackerBlocker too so the alert gets the right title?

<img width="244" alt="image" src="https://user-images.githubusercontent.com/3763465/109492022-9e9b8580-7a8a-11eb-8125-abc1995e62aa.png">

**Comment by apparition47** [comment]
Oops 😅

**Comment by apparition47** [comment]
Thanks again

**Comment by larkov** [comment]
Just so that you are aware of it. The alert image used in the readme.md has the typo in it. 😄
