### ISSUE TITLE
Have documentation show what a blocked tracker looks like. (And other comments)

### ISSUE THREAD

**Issue by DHKaplan** [apparition47/MailTrackerBlocker#48]
Just downloaded your plugin as mentioned in https://www.lifewire.com/how-your-email-might-be-spying-on-you-5114642. It would be nice to see an example screenshot of what a positive hit looks like. 

I also noticed that the manage plugins button didn't show up until I installed the plugin. You might want to mention that.

Finally, is there any way to test this, as a user?

Thanks for filling this void in security.

**Comment by apparition47** [comment]
Nice, thanks for sharing that article!

There's this screenshot on the README and on the homepage. That's what a hit looks like.

![](https://user-images.githubusercontent.com/3298414/109422170-c4d70c00-7a1d-11eb-9e5a-bf5a8e36d16d.jpg)

If you'd like to prove to yourself that it works like I have done, you can use a tracking service (I usually test with MailTrack), then send an email to yourself

<img width="765" alt="Sent_Mail_-_aaronl87_gmail_com_-_Gmail" src="https://user-images.githubusercontent.com/3298414/109660399-2927d600-7bac-11eb-95c8-2445185da5c0.png">

**Comment by apparition47** [comment]
Also:
![](https://user-images.githubusercontent.com/47551890/89727857-6d625600-da63-11ea-91b9-90f48301dc05.png)

**Comment by DHKaplan** [comment]
Thanks, just checked a few emails and it's terrifying whose tracking us... : (

**Comment by apparition47** [comment]
Indeed 😱

>I also noticed that the manage plugins button didn't show up until I installed the plugin. You might want to mention that.

Probably will include something during the install process to highlight this. Thanks!
