### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by burnout-syndrome** [apparition47/MailTrackerBlocker#5]
I still get the _"MailTrackerBlocker.pkg" can't be opened because Apple cannot check it for malicious software.
This softare needs to be updated. Contact the developer for more information._ - notification with the latest version.

**Comment by apparition47** [comment]
Thanks for taking the time to open an issue. This has already been reported (#1) and is still an open issue I'm still looking into. For the time being, you'll have make an exception through the security/Gatekeeper settings to install, sorry 😞

**Comment by burnout-syndrome** [comment]
Ah, I see. Thank you for the quick reply!
