### ISSUE TITLE
Different ConvertKit Tracker

### ISSUE THREAD

**Issue by dotsam** [apparition47/MailTrackerBlocker#55]
Found a ConvertKit tracker that's not detected by the current rule for that service or by any generic rules

```
<img src="https://open.convertkit-mail2.com/[a-z0-9]{20}" alt="" style="display:block;margin-bottom:32px">
```

(ID replaced with a matching regex)

**Comment by apparition47** [comment]
>margin-bottom:32px

A bit odd they're using this as a spacer too. What does this image look like? Is this image a pixel in size?

**Comment by dotsam** [comment]
This is the very last element in the body of the message, and does seem to be adding the padding to the bottom of the message, yes

**Comment by dotsam** [comment]
(Oh, but the image itself is a 1x1 transparent GIF, yes)

**Comment by apparition47** [comment]
Thanks for confirm that. Just wanted to confirm it's wasn't a horizontal spacer image or something. Will include this soon.
