### ISSUE TITLE
After installing on High Sierra, "Manage Plug-ins" button is not displayed in Mail prefs

### ISSUE THREAD

**Issue by beyondmany** [apparition47/MailTrackerBlocker#57]
1. High Sierra
2. Install latest build (as of 3-2-21)
3. Launch Mail.
4. Go to Preferences->General

Observation:
1. The button "Manage Plug-ins" does not appear in the mail app.
2. Quitting Mail app and reinstalling the plugin has no effect.

**Comment by apparition47** [comment]
Thanks for reporting. Going to move this to #50 as there are others with this issue as well.
