### ISSUE TITLE
Not detecting trackers from mkt81(dot)net

### ISSUE THREAD

**Issue by polarweasel** [apparition47/MailTrackerBlocker#58]
Just noticed in an email from my bank, down at the very bottom, directly before the `</body>` closing tag:

```
<IMG src="https://open.mkt81.net/open/log/[[redacted for my privacy]]" style="display: none">
```

Looking through the rest of the source, it appears [[redacted for my privacy]] is of the form: `campaignID/userID/integer/jobID/integer/integer`

**Comment by apparition47** [comment]
Appreciate your contribution. This will be handled soon. Thanks!

**Comment by polarweasel** [comment]
I'm curious to know how you're handling patterns. Are you blacklisting particular hosts, or are you trying to stay to a strict "look for hidden or single-pixel elements" approach? I'd like to contribute PRs as I find things, if I can...

**Comment by polarweasel** [comment]
NM, found my own answer reading Source/MTBBlockedMessage.m 😁

**Comment by apparition47** [comment]
I have a regex list for specific hosts to label and identify them plus a fallback for single-pixel images. [MailTrackerBlocker started out with this list by **dhh** and they use it in HEY](https://gist.github.com/dhh/360f4dc7ddbce786f8e82b97cdad9d20). From personal experience, it seems to be quite good at catching a good chunk of trackers.

**Comment by apparition47** [comment]
[These guys (acoustic) have quite a collection of domains](https://fossies.org/linux/ntopng/httpdocs/other/trackers.txt). Will address this one. Thanks again.
