### ISSUE TITLE
GPG-Tools Plugin is not working with activated MacTracker Plugin

### ISSUE THREAD

**Issue by Chuby1** [apparition47/MailTrackerBlocker#6]
Sorry for posting into the wrong thread...
The attached screenshot shows the problem that I have been faced with when I have installed and activated your Plugin. WOuld be great if you are able to solve this problem. Thanks and regards Chuby

<img width="639" alt="Bildschirmfoto 2020-07-31 um 19 45 37" src="https://user-images.githubusercontent.com/69050286/89062390-a49b7d80-d366-11ea-935f-89346ac951ca.png">

<img width="649" alt="Bildschirmfoto 2020-07-31 um 19 48 54" src="https://user-images.githubusercontent.com/69050286/89062528-e75d5580-d366-11ea-9303-cc36516fb3b2.png">

EDIT: I have installed your Plugin on a MacBookPro 16 with Catalina 10.15.6. Unfortunatly the Plugin for the "GPG-Tools" does not work anymore now. Received encrypted mails will not be shown decrypted as long as your plugin is active.
Deactivating your plugin and restarting Apple Mail will make the Plugin for the GPG-Tools working again.

Just tried 0.2.5 but it´s the same than before. The GPG-Tools Plugin
is not working…

**Comment by apparition47** [comment]
@Chuby1 Will look into it

**Comment by apparition47** [comment]
Hi @Chuby1, found the issue. Could you try this and let me know if it works in your case? Install: [MailTrackerBlocker-develop.pkg.zip](https://github.com/apparition47/MailTrackerBlocker/files/5011675/MailTrackerBlocker.pkg.zip).

**Comment by Chuby1** [comment]
Hi @Aaron, seems to be that you´ve solved this problem :) I installed
your developer version and it works. The encrypted mails that I receive
are shown decrypted from the GPG-Tools plugin even if your plugin actived.

So thank you very much. Chuby

**Comment by apparition47** [comment]
Thanks for checking. Released as [0.2.6](https://github.com/apparition47/MailTrackerBlocker/releases/tag/0.2.6).
