### ISSUE TITLE
Add support for blocking Mailcastr spy pixels

### ISSUE THREAD

**Issue by k4rtik** [apparition47/MailTrackerBlocker#60]
Thanks for this useful plugin.

I did not find instructions to send a PR to add a new tracker, so I am just opening an issue for now.

I received an email with a tracking signature that looks like this:

> https://mailcastr.com/image/MTEyODc4MDkwMDkyMDIzOTA4ODc3Ojo6NjBlMTEzZmY3YzJhNdhYzk2NzkwMTE0ODhmNGI0NzQ6OnY0OjoxNjE0ODA0OTMzOjox/

which is a 1x1 invisible JPEG.

The only reason I knew there might be email tracking was that the body of the message also had the following in the signature:

> ![image](https://user-images.githubusercontent.com/374340/109975097-e0f9d800-7cbf-11eb-98e4-2930d8478264.png) Sent with [Mailcastr](https://mailcastr.com/?utm_source=browser-extension&utm_medium=branded-email&utm_campaign=BRANDING)

**Comment by apparition47** [comment]
Thanks for your submission. 

Just for posterity, can you share the the entire HTML tag for that tracker? You can find that by going to: `Message > Raw Source`. Also, did MailTrackerBlocker detect the tracker (solid grey)? Or not at all (bordered grey)?

**Comment by k4rtik** [comment]
Sure:

```
    <tbody>
      <tr>
        <td>
            <img width=3D"24" height=3D"24" style=3D"width:24px;height:24px=
;" src=3D"https://mailcastr.com/static/web/images/logo-48px.png?t=3D1544177=
822751" alt=3D"mailcastr branding">
            </td>
        <td>
            <span>Sent with <a href=3D"https://mailcastr.com/?utm_source=3D=
browser-extension&amp;utm_medium=3Dbranded-email&amp;utm_campaign=3DBRANDIN=
G" target=3D"__blank">Mailcastr</a></span>
        </td>
      </tr>
    </tbody>
  </table></div></div><img style=3D"border:none;" name=3D"mtimg" src=3D"htt=
ps://mailcastr.com/image/MTEyODc4MDkwMDkyMDIzOTA4ODc3Ojo6NjBlMTEzZmY3YzJhND=
dhYzk2NzkwMTE0ODhmNGI0NzQ6OnY0OjoxNjE0ODA0OTMzOjox/"></div><br><div class=
=3D"gmail_quote"><div dir=3D"ltr" class=3D"gmail_attr">On Wed, Mar 3, 2021 =
at 1:59 PM Kartik Singhal &lt;<a href=3D"mailto:XXX@XXX.XXX">XXX@XX.X=
XXX</a>&gt; wrote:<br></div>
```

I can't tell the color difference, but when I click on it, I see:

![image](https://user-images.githubusercontent.com/374340/109988779-7cde1080-7ccd-11eb-8fd8-edc8875e9f04.png)

**Comment by apparition47** [comment]
Thanks! This will be included soon.
