### ISSUE TITLE
If pgrep returns several pids, Mail won't restart after installation.

### ISSUE THREAD

**Issue by larkov** [apparition47/MailTrackerBlocker#68]
If pgrep returns several pids the if statement fails and postinstall won't restart Mail.

https://github.com/apparition47/MailTrackerBlocker/blob/38c5dfab0b72768aa5afa523300af9dc505e6072/Packaging/preinstall#L7

Submitting pull request to fix this shortly.

**Comment by apparition47** [comment]
Thanks again!
