### ISSUE TITLE
URLs being rewritten as invalid URLs

### ISSUE THREAD

**Issue by cmod** [apparition47/MailTrackerBlocker#70]
It seems like MailChimp and some other service URLs which are seen as tracking as being rewritten by MailTrackerBlocker are being rewritten in a way that breaks the URLs. 

If I disable MailTrackerBlocker the URLs resolve as expected.

**Comment by cmod** [comment]
(Disregard — I just updated and it seems to be fixed in latest version)

**Comment by apparition47** [comment]
If you see this behaviour, please post the `Raw Message Source` so I can correct the rules. This shouldn't be happening.

**Comment by cmod** [comment]
Will do. It just started happening two days ago but, like I said, the update seems to have fixed it.

(It looks like TLDs were being chopped off of URLs — i.e., the root url would end with https://[something]./[restofurl])

**Comment by apparition47** [comment]
Ah I see. Just to add to the above: only tracker image URLs are supposed to be rewritten (admittedly crude but seems to work fairly well). Normal links are supposed to remain intact. I also try to release updates to the rules once in a while.

Feel free to reopen if you have this issue!
