### ISSUE TITLE
URLs being rewritten as invalid URLs

### ISSUE THREAD

**Issue by m-schmitt** [apparition47/MailTrackerBlocker#76]
[City of Frisco’s Vaccine Scheduling Site Open for Appointments March 17-18.eml.txt](https://github.com/apparition47/MailTrackerBlocker/files/6143696/City.of.Frisco.s.Vaccine.Scheduling.Site.Open.for.Appointments.March.17-18.eml.txt)
Attached is an email where a non-image link https://friscotexas.us4.list-manage.com/track/click?u=33cd614c011fb86a5e16e4f59&id=8d0048bd24&e=67a88b413c was rewritten as an invalid URL https://friscotexas.us4./click?u=33cd614c011fb86a5e16e4f59&id=8d0048bd24&e=67a88b413c.

**Comment by apparition47** [comment]
Thanks for the email. Will look into this

**Comment by apparition47** [comment]
Fixed in 0.3.22

**Comment by m-schmitt** [comment]
I think fewer links are broken, but in the sample email the first now still is. I think it's the link that starts on line 984 and ends on line 985:

 </strong>To book an appointment <a href=3D"**https://FriscoTexas.us4.list-m=
anage.com**/track/click?u=3D33cd614c011fb86a5e16e4f59&id=3D8d0048bd24&e=3D67a8

**Comment by apparition47** [comment]
Oops, accidentally left out my fix in `0.3.22`. Should be OK now in `0.3.23`. Sorry!

**Comment by m-schmitt** [comment]
That worked, thanks!
