### ISSUE TITLE
Misses Google tracker

### ISSUE THREAD

**Issue by j-f1** [apparition47/MailTrackerBlocker#80]
“MailTrackerBlocker did not detect any trackers in this email.”

```html
<img alt="" height=1 width=3 src=https://notifications.google.com/g/img/AD-FnEzt8doYQCTNQv1w6jsjHDU6Kh6lId34t0STSV3ydKTDIw.gif>
```

**Comment by apparition47** [comment]
Interesting. Had no idea excluding quotations is still valid HTML. For context, which Google product did you see this in?

**Comment by j-f1** [comment]
Google Analytics

**Comment by apparition47** [comment]
Thanks for reporting. Added this to 0.3.22.
