### ISSUE TITLE
CNN Mail tracker?

### ISSUE THREAD

**Issue by DHKaplan** [apparition47/MailTrackerBlocker#93]
I've been enjoying the blocker for a few weeks now. I just received an email from CNN saying I hadn't opened their daily email to me for awhile and did I want to continue to receive it. (They wouldn't cut me off, but said I could resubscribe). I looked at the email and the MailTrackerBlocker says that there are no trackers. I've attached both emails... Any thoughts? Apparently I can't attach eml files, so I renamed them txt.
[We’ve missed you!.txt](https://github.com/apparition47/MailTrackerBlocker/files/6222071/We.ve.missed.you.txt)
[Infrastructure is about to put Biden's bipartisan appeal to the test.txt](https://github.com/apparition47/MailTrackerBlocker/files/6222072/Infrastructure.is.about.to.put.Biden.s.bipartisan.appeal.to.the.test.txt)

**Comment by apparition47** [comment]
Thanks for sharing. The first email has a tracker provided by `Live Intent`. The second email has **two** trackers in it (via `Live Intent` and `Zeta Global`). Yikes.

Anyhow, I patched a rule for these into 0.3.26.
