### ISSUE TITLE
[O/T] any contributor who can solve mailflow installation problems?

### ISSUE THREAD

**Issue by JayBrown** [apparition47/MailTrackerBlocker#94]
I know this is off-topic, but we seem to be stuck trying to install the mailflow python2.7-based Mail bundle on Big Sur. If anyone can help out, it would be much appreciated.

https://github.com/arachsys/mailflow

There is no Issues section there, but a small discussion can be found in one of the pull request topics here: https://github.com/arachsys/mailflow/pull/3

**Comment by apparition47** [comment]
General advice: Copy the UUIDs from my `Info.plist` then read my `postinstall`.

For Big Sur, the mailbundle also has to be signed and notarized.

**Comment by JayBrown** [comment]
Line 1: yep, did that
Line 2: that seems to be the problem then… signing & notarization… but how do developers test their mailbundles? Always properly sign & notarize before any testing?

**Comment by apparition47** [comment]
I develop on a 10.15 machine but if you need to test on Big Sur, you can just [copy the mailbundle to: "/Users/${USER}/Library/Application\ Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles" using Finder](https://github.com/apparition47/MailTrackerBlocker/blob/main/Packaging/postinstall#L73)

**Comment by apparition47** [comment]
@JayBrown Again, feel free to knock off my Finder Apple Script. You can also see my GitHub Actions workflow to see how I setup my pkg installer too.

The whole process is essentially:

1. Include the Mail.app UUIDs in Info.plist
2. compile with Xcode 12 against Big Sur's Mail.app for arm64 (e.g. Apple Silicon) support, enable hardened runtimes (everything to pass notarization)
3. package everything into a pkg
4. sign and notarize (then staple) the whole pkg
5. the pkg contains a postinstall script which: quits mail, copies the mailbundle to `/Library/Mail/Bundles/` then:
 * [Big Sur only] copies it also to `~/Library/Application\ Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles`
 * or [10.15 and below] runs `codesign --remove-signature` on the mailbundle
