### ISSUE TITLE
Post-installation instructions should specify 10.14 or later, not just 10.14 and 10.15

### ISSUE THREAD

**Issue by gruber** [apparition47/MailTrackerBlocker#98]
After running the installer, instructions are shown for enabling the plug-in in Mail's preferences. These instructions start: "[Additional step for macOS 10.14, 10.15 only]".

But this is outdated — this is required on macOS 11 Big Sir too. I suggest changing the instructions to read "Additional step for macOS 10.14 or later".

![instructions](https://user-images.githubusercontent.com/12223/113456113-5e595b00-93da-11eb-9c1f-9e8a3e105e11.png)

**Comment by apparition47** [comment]
Starting from version `0.3.22`, the installer has an Apple Script/Finder process for Big Sur users to auto-enable the plugin without those aforementioned manual steps for your user.
<img width="420" alt="Screen Shot 2021-04-03 at 1 50 23 PM" src="https://user-images.githubusercontent.com/3298414/113468822-91a3f480-9483-11eb-898e-3f1e74c125aa.png"><img width="260" alt="Screen Shot 2021-04-03 at 1 50 26 PM" src="https://user-images.githubusercontent.com/3298414/113468821-8fda3100-9483-11eb-9fe8-9e55a189b27f.png">

But I suppose if you (1) hit `Don't Allow` or (2) switch to a different user and try to use Mail, then you'll need to manually enable the plugin as per the usual steps.

**Comment by apparition47** [comment]
Tried to clarify instructions a bit more on the homepage as well. Hope it makes sense; haven't gotten any complaints yet.

Appreciate you dropping by again! Thanks!
